'use client'
import { useEffect, useRef, useState } from 'react'
import Link from 'next/link'
import UploadPanel from '@/components/chat/UploadPanel'
import IntakeProgress from '@/components/chat/IntakeProgress'
import QuoteView from '@/components/quote/QuoteView'
import { TRADE_CATEGORIES } from '@/lib/trade-taxonomy'
import '@/components/profitability/profitability.css'
export default function JobDrawings({jobId}:{jobId:string}){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[upload,setUpload]=useState(false),[manual,setManual]=useState(''),[run,setRun]=useState<any>(null),[quote,setQuote]=useState<string|null>(null),[clear,setClear]=useState<string|null>(null)
 const [answers,setAnswers]=useState<Record<string,string>>({}),[question,setQuestion]=useState(''),[answer,setAnswer]=useState('')
 const request=useRef<string|null>(null), endpoint=`/api/jobs/${jobId}/drawings`
 async function load(){const r=await fetch(endpoint),d=await r.json();if(!r.ok)throw Error(d.error);setData(d)}
 useEffect(()=>{load().catch(e=>setError(e.message))},[endpoint]) // eslint-disable-line react-hooks/exhaustive-deps
 async function act(body:any){setBusy(true);setError('');try{const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw Error(d.error);await load();return d}catch(e){setError((e as Error).message);return null}finally{setBusy(false)}}
 async function refresh(){request.current??=crypto.randomUUID();const d=await act({action:'refresh',request_id:request.current,manual_policy:manual});if(d)setRun(d.run)}
 return <main className="pi"><Link href={`/jobs/${jobId}`}>← Back to job</Link><h1>Plans and estimate versions</h1><p>{data?.job.address??'Loading…'}</p><p className="muted">Upload → review the drawing set → confirm answers → refresh the estimate. Uploading a file does not mean the estimate is complete.</p>{error&&<p className="pi-alert pi-error" role="alert">{error}</p>}
 <button className="primary" disabled={!data||busy} onClick={()=>setUpload(true)}>Update plans</button>
 <section className="pi-card"><h2>Review uploaded drawings</h2><p>Choose whether each new document adds to the set or replaces a whole existing document. For a PDF containing multiple sheets, review all sheets before replacing it. If the relationship is uncertain, leave it unresolved.</p>{data?.files.map((f:any)=><div key={f.id} className="py-3 border-b"><a href={`/api/jobs/${jobId}/files/${f.id}`} target="_blank" rel="noreferrer">{f.filename}</a><p>{f.drawing_state}{f.duplicate_of_file_id?` · Exact duplicate of ${data.files.find((x:any)=>x.id===f.duplicate_of_file_id)?.filename??'a retained file'} — excluded from estimating`:''}</p>{f.drawing_state==='unresolved'&&<div className="flex flex-wrap gap-2"><button disabled={busy||!f.content_hash} onClick={()=>act({action:'reconcile',file_id:f.id,relationship:'add'})}>Add to current set</button><label>Replace document<select disabled={busy||!f.content_hash} defaultValue="" onChange={e=>{if(e.target.value)void act({action:'reconcile',file_id:f.id,relationship:'replace',replaces:e.target.value})}}><option value="">Choose existing document…</option>{data.files.filter((x:any)=>x.drawing_state==='current'&&x.id!==f.id).map((x:any)=><option value={x.id} key={x.id}>{x.filename}</option>)}</select></label><button disabled={busy} onClick={()=>act({action:'reconcile',file_id:f.id,relationship:'evidence'})}>Keep as supporting evidence only</button>{!f.content_hash&&<button disabled={busy} onClick={()=>act({action:'finalise',file_id:f.id})}>Verify completed upload</button>}</div>}</div>)}{data?.files.length===0&&<p>No plans yet. Upload the issued plans and specifications to start.</p>}</section>
 <section className="pi-card"><h2>Confirmed job answers</h2><p>These are job-specific facts, retained across estimate versions. Revised plans prompt you to review them; they are not business defaults.</p>{data?.facts.map((f:any)=><div key={f.id} className="py-3"><label className="pi-field">{f.key}{f.review_required?' · Review against revised plans':''}<textarea value={answers[f.id]??f.value} onChange={e=>setAnswers({...answers,[f.id]:e.target.value})}/></label><button disabled={busy} onClick={()=>act({action:'answer',fact_id:f.id,answer:answers[f.id]??f.value})}>Confirm answer for current plans</button></div>)}<label className="pi-field">Question / fact name<input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Does the tile allowance include installation?"/></label><label className="pi-field">Builder-confirmed answer<textarea value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Supply only; installation priced separately."/></label><button disabled={busy||!question||!answer} onClick={async()=>{if(await act({action:'answer',question,answer})){setQuestion('');setAnswer('')}}}>Save job answer</button></section>
 <section className="pi-card"><h2>Refresh estimate</h2><p>Creates a new draft from the current drawing set. Original files, previous versions, actual costs and the approved contract remain preserved.</p><label className="pi-field">Existing manually priced items<select value={manual} onChange={e=>setManual(e.target.value)}><option value="">Choose how to handle manual items</option><option value="retain">Retain manual items — I reviewed them against the selected plans</option><option value="review">Generate afresh — re-enter manual overrides after review</option></select></label><button disabled={busy||!manual||!data||!!run||data.files.some((f:any)=>f.drawing_state==='unresolved')||data.facts.some((f:any)=>f.review_required)} className="primary" onClick={refresh}>{busy?'Saving request…':'Refresh estimate from current plans'}</button></section>
 {run&&data&&<IntakeProgress fileId={run.file_ids[0]} additionalFileIds={run.file_ids.slice(1)} jobId={jobId} builderId={data.job.builder_id} filename="Current drawing set" onComplete={id=>{setRun(null);request.current=null;setQuote(id);void load()}} onError={message=>setError(message??'Processing paused. Use the saved progress controls to retry.')}/>}
 {data?.runs.map((r:any)=><section className="pi-card" key={r.id}><h2>Estimate refresh · {new Date(r.created_at).toLocaleDateString('en-AU')}</h2><p>{r.file_ids.map((id:string)=>data.files.find((f:any)=>f.id===id)?.filename??'Retained source document').join(', ')} · {r.manual_policy==='retain'?'Manual items retained':'Fresh pricing requested'}</p><button onClick={()=>setQuote(r.draft_quote_id)}>Review draft</button><button disabled={busy||!!run||!!r.cleared_at} onClick={()=>setRun(r)}>View processing / safe retry</button>{r.cleared_at&&<p>This draft was cleared. Use Refresh estimate above to regenerate a new version.</p>}<button onClick={()=>setClear(r.draft_quote_id)}>Clear generated draft items</button><div className="pi-scroll"><table><thead><tr><th>Trade</th><th>Previous cost</th><th>Revised cost</th><th>Cost change</th></tr></thead><tbody>{TRADE_CATEGORIES.map(t=>{const prev=r.previous_items.filter((x:any)=>x.trade_category_id===t.id&&x.assumption_status!=='excluded'&&!x.variation_id),next=r.items.filter((x:any)=>x.trade_category_id===t.id&&x.assumption_status!=='excluded'&&!x.variation_id);const total=(list:any[])=>!list.length||list.some(x=>x.total===null)?'Incomplete':list.reduce((s,x)=>s+Number(x.total),0).toLocaleString('en-AU',{style:'currency',currency:'AUD'});return <tr key={t.id}><td>{t.name}</td><td>{total(prev)}</td><td>{total(next)}</td><td>{prev.length&&next.length&&prev.every((x:any)=>x.total!=null)&&next.every((x:any)=>x.total!=null)?(next.reduce((s:number,x:any)=>s+Number(x.total),0)-prev.reduce((s:number,x:any)=>s+Number(x.total),0)).toLocaleString('en-AU',{style:'currency',currency:'AUD'}):'Not comparable yet'}</td></tr>})}</tbody></table></div></section>)}
 {clear&&<section className="pi-card" role="alert"><h2>Clear this draft’s generated items?</h2><p>A snapshot is retained. Plans, confirmed facts, manual items, approved estimates, variations and actual costs remain. A saved contract baseline cannot be cleared.</p><button disabled={busy} onClick={async()=>{if(await act({action:'clear',quote_id:clear,confirmed:true}))setClear(null)}}>Confirm clear generated draft</button><button onClick={()=>setClear(null)}>Keep draft</button></section>}
 {data&&<UploadPanel isOpen={upload} onClose={()=>setUpload(false)} job={data.job} builderId={data.job.builder_id}/>}
 {quote&&data&&<QuoteView quoteId={quote} builderId={data.job.builder_id} onClose={()=>setQuote(null)} onSend={()=>setQuote(null)} onRevise={id=>setQuote(id)} onExportPdf={id=>window.open(`/api/quotes/${id}/export-pdf`,'_blank')}/>}
 </main>
}
