'use client'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import JobPhotoUpload from './JobPhotoUpload'
import { WORKFLOW_KINDS, programmeReadiness, type WorkflowKind, type WorkflowRecord } from '@/lib/job-workflow'
import { TRADE_CATEGORIES } from '@/lib/trade-taxonomy'
import '@/components/profitability/profitability.css'

const labels: Record<WorkflowKind,string> = { purchase_order:'Purchase order', bill:'Supplier bill / credit', selection:'Selection & tile scenario', programme:'Programme activity', scope_pack:'Trade scope pack', site_update:'Site update / issue', question:'Question / approval needed', deadline:'Business deadline', trade_quote:'Trade quote', material_transfer:'Move materials between jobs' }
const quickActions: [WorkflowKind, string, string][] = [
 ['bill','Add a bill or credit','Record a supplier invoice against this job.'],
 ['selection','Check a tile change','See the cost before preparing a variation.'],
 ['trade_quote','Add a trade quote','Save a price and what it covers.'],
 ['site_update','Record a site update','Capture an issue and who will handle it.'],
]
const essentials: Partial<Record<WorkflowKind,string[]>> = {
 bill:['supplier','invoice_ref','source_amount','tax_basis','evidence','po_id','release_amount','match_reviewed'],
 purchase_order:['supplier','source_amount','tax_basis','due_on'],
 trade_quote:['supplier','source_amount','tax_basis','inclusions','exclusions'],
 programme:['owner','start_on','finish_on','dependencies','readiness'],
 selection:['room','area','original_rate','original_gst','proposed_rate','proposed_gst','price_basis','installation','wastage_pct','extras','extra_evidence','markup_pct','reviewed'],
}
type Field = [string,string,string?]
const fields: Record<WorkflowKind,Field[]> = {
 material_transfer:[['to_job_id','Receiving job','job'],['source_amount','Transferred material value','number'],['tax_basis','GST basis','gst'],['evidence','Material, quantity, original supplier and valuation evidence','textarea']],
 purchase_order:[['supplier','Supplier'],['source_amount','Expected source amount','number'],['tax_basis','GST basis','gst'],['due_on','Delivery expected','date'],['access','Delivery and site access notes'],['reference','Supplier quote reference']],
 bill:[['supplier','Supplier'],['invoice_ref','Invoice / credit reference'],['source_amount','Signed source amount (negative for credit)','number'],['tax_basis','GST basis','gst'],['invoice_on','Invoice / credit date (today if omitted)','date'],['due_on','Payment due','date'],['po_id','Matching purchase order','po'],['release_amount','Outstanding commitment replaced, AUD ex GST','number'],['evidence','Invoice evidence / pasted invoice text','textarea'],['accepted_quote_id','Subcontractor accepted quote (for claims)','quote'],['percent_complete','Subcontractor reported completion % (if supplied)','number'],['labour_hours','Labour hours explicitly supplied (if available)','number'],['match_reviewed','I reviewed differences from the supplier order or accepted quote','checkbox']],
 trade_quote:[['supplier','Trade / supplier'],['source_amount','Quoted source amount','number'],['tax_basis','GST basis','gst'],['reference','Quote reference and date'],['inclusions','Quoted inclusions','textarea'],['exclusions','Qualifications / exclusions','textarea']],
 selection:[['room','Room / affected work'],['area','Measured tile area m²','number'],['original_rate','Original price per m²','number'],['original_gst','Original GST basis','gst'],['proposed_rate','Proposed price per m²','number'],['proposed_gst','Proposed GST basis','gst'],['price_basis','What do these prices represent?','basis'],['installation','Installation treatment','installation'],['wastage_pct','Confirmed wastage %','number'],['extras','Other evidenced cost adjustment, AUD ex GST (enter 0 if none)','number'],['extra_evidence','Delivery, labour, orders, deposits and return-cost evidence','textarea'],['markup_pct','Builder markup on additional cost %','number'],['programme_effect','Known programme effect or information still needed'],['lead_time','Confirmed procurement lead time (leave unknown if not supplied)'],['due_on','Client decision needed by','date'],['activity_id','Affected activity','activity'],['owner','Decision owner'],['reviewed','I reviewed all costs, orders, pricing and programme assumptions','checkbox']],
 programme:[['owner','Responsible person / trade'],['start_on','Proposed start','date'],['finish_on','Proposed finish','date'],['dependencies','Depends on completed activities','dependencies'],['readiness','Readiness conditions and hold points','textarea'],['notes','Return visits and booking notes','textarea']],
 scope_pack:[['purpose','Pack purpose','purpose'],['arrangement','Supply arrangement','arrangement'],['accepted_quote_id','Accepted trade quote','quote'],['inclusions','Scope inclusions and work areas','textarea'],['exclusions','Exclusions and work by others','textarea'],['responsibilities','Supply, access equipment and protection responsibilities','textarea'],['specification_ref','Issued specification / finish reference'],['finish_standard','Observable definition of done','textarea'],['clean_up','Daily cleanliness and final clean-up','textarea'],['hold_points','Hold points, inspections and release requirements','textarea'],['owner','Trade contact'],['start_on','Proposed start','date'],['finish_on','Proposed finish','date'],['activity_id','Programme activity','activity'],['questions','Unresolved questions, owner and required-by dates','textarea'],['agreements','Existing agreement / site-rule references (if available)'],['acknowledgement','Trade acknowledgement, person and date'],['completion_evidence','Builder release / sign-off evidence'],['defects','Outstanding defects and handover evidence'],['file_ids','Current drawings and supporting attachments','files']],
 site_update:[['location','Room / location'],['owner','Proposed issue owner'],['due_on','Next action due','date'],['notes','What happened / what needs fixing?','textarea'],['next_action','Proposed next action'],['file_ids','Photos / evidence already uploaded to this job','files']],
 question:[['owner','Waiting on whom?'],['due_on','Answer required by','date'],['notes','Question and source correspondence','textarea'],['activity_id','Affected activity','activity'],['answer','Confirmed answer (if received)','textarea']],
 deadline:[['owner','Responsible person'],['due_on','Due date','date'],['notes','Claim, renewal or inspection details','textarea'],['next_action','Next action'],['activity_id','Related programme activity','activity']],
}
const currency = (n: number | null | undefined) => n == null ? 'Not established' : n.toLocaleString('en-AU',{style:'currency',currency:'AUD'})
const date = (s: string) => s ? new Date(s+'T12:00:00').toLocaleDateString('en-AU') : 'Date not set'
export default function JobWorkflow({jobId}:{jobId:string}) {
 const [quoteToUse,setQuoteToUse]=useState(''),[itemsToReplace,setItemsToReplace]=useState<string[]>([])
 const [chat,setChat]=useState(''),[reply,setReply]=useState(''),[formBasis,setFormBasis]=useState<number|null>(null),[completion,setCompletion]=useState<Record<string,{completion_evidence?:string;acknowledgement?:string}>>({})
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
 const [kind,setKind]=useState<WorkflowKind>('purchase_order'),[filter,setFilter]=useState('all'),[editing,setEditing]=useState<WorkflowRecord|null>(null)
 const [title,setTitle]=useState(''),[payload,setPayload]=useState<Record<string,any>>({}),[draftId,setDraftId]=useState(''),[formOpen,setFormOpen]=useState(false)
 const endpoint=`/api/jobs/${jobId}/workflow`, records:WorkflowRecord[]=data?.records??[]
 useEffect(()=>{if(data&&location.hash)document.getElementById(decodeURIComponent(location.hash.slice(1)))?.scrollIntoView({block:'start'})},[data])
 const today = new Date().toLocaleDateString('en-CA',{timeZone:'Australia/Sydney'})
 async function load(){const response=await fetch(endpoint);const body=await response.json();if(!response.ok)throw Error(body.error);setData(body)}
 useEffect(()=>{load().catch(e=>setError(e.message))},[endpoint]) // eslint-disable-line react-hooks/exhaustive-deps
 function start(k:WorkflowKind,r?:WorkflowRecord){setFormBasis(data?.job.profitability_revision??null);setKind(k);setEditing(r??null);setTitle(r?.title??'');setPayload(r?.payload??{});setDraftId(r?.id??crypto.randomUUID());setFormOpen(true);setError('');requestAnimationFrame(()=>document.getElementById('job-record-editor')?.scrollIntoView({block:'start',behavior:'smooth'}))}
 async function submit(action:string,r?:WorkflowRecord){
  setBusy(true);setError('');setNotice('')
  try {
   const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,id:r?.id??draftId,version:r?.version??editing?.version??0,kind:r?.kind??kind,title:r?.title??(title.trim()||[labels[kind],payload.supplier||payload.room||payload.owner].filter(Boolean).join(' — ')),payload:action==='complete'?{...r?.payload,...completion[r!.id]}:r?.payload??payload,basis_revision:action==='save'?formBasis:data.job.profitability_revision})})
   const body=await response.json();if(!response.ok)throw Error(body.error)
   if(action==='save')setFormOpen(false)
   setNotice(action==='confirm'?(r?.kind==='selection'?'Variation draft prepared. Client approval is still required.':'Confirmed and recorded. No message was sent.'):'Saved.');await load()
  }catch(e){setError((e as Error).message)}finally{setBusy(false)}
 }
 async function applyTrade(r:WorkflowRecord){setBusy(true);setError('');try{const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'apply_trade_quote',id:r.id,version:r.version,quote_id:quoteToUse,item_ids:itemsToReplace})}),d=await response.json();if(!response.ok)throw Error(d.error);await load();setItemsToReplace([]);setNotice('Accepted quote incorporated into the selected draft. Review pricing before issue.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function ask(){setBusy(true);setError('');try{const r=await fetch(`/api/jobs/${jobId}/assistant`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:chat})}),d=await r.json();if(!r.ok)throw Error(d.error);setReply(d.message);if(d.proposal){start(d.proposal.kind);setTitle(d.proposal.title);setPayload(d.proposal.payload);setFormBasis(d.basis_revision)}}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function change(k:string,v:any){setPayload(p=>({...p,[k]:v}))}
 function field([key,label,type='text']:Field){
  const options:Record<string,[string,string][]>={gst:[['exclusive','AUD excluding GST'],['inclusive','AUD including GST']],basis:[['purchase_cost','Supplier purchase costs'],['client_allowance','Client-facing allowance — purchase costs needed']],installation:[['supply_only','Both supply only; installation reviewed separately'],['same_installation','Same installation included in both prices']],purpose:[['request_quote','Request a quote'],['appointed','Brief appointed trade']],arrangement:[['labour_only','Labour only'],['supply_install','Supply and install'],['split','Explicit split — describe below']]}
  const linked=type==='job'?(data?.jobs??[]).filter((j:any)=>j.id!==jobId).map((j:any)=>({id:j.id,title:j.address})):type==='po'?records.filter(r=>r.kind==='purchase_order'&&r.status==='confirmed'):type==='quote'?records.filter(r=>r.kind==='trade_quote'&&r.status==='confirmed'):records.filter(r=>r.kind==='programme'&&r.id!==draftId)
  if(['files','dependencies'].includes(type)){const choices=type==='files'?(data?.files??[]).filter((f:any)=>['current','evidence'].includes(f.drawing_state)).map((f:any)=>({id:f.id,title:f.filename})):linked;return <fieldset key={key} className="pi-card"><legend>{label}</legend>{choices.map((c:any)=><label className="pi-check" key={c.id}><input type="checkbox" checked={(payload[key]??[]).includes(c.id)} onChange={e=>change(key,e.target.checked?[...(payload[key]??[]),c.id]:(payload[key]??[]).filter((id:string)=>id!==c.id))}/>{c.title}</label>)}{!choices.length&&<p>No records yet. Save the related record first.</p>}</fieldset>}
  if(type==='checkbox')return <label key={key} className="pi-check"><input type="checkbox" checked={payload[key]===true} onChange={e=>change(key,e.target.checked)}/>{label}</label>
  return <label key={key} className="pi-field"><span>{label}</span>{options[type]||['po','quote','activity','job'].includes(type)?<select value={payload[key]??''} onChange={e=>change(key,e.target.value)}><option value="">Choose / not yet known</option>{(options[type]??linked.map((r:{id:string;title:string})=>[r.id,r.title])).map(([value,name])=><option key={value} value={value}>{name}</option>)}</select>:type==='textarea'?<textarea value={payload[key]??''} onChange={e=>change(key,e.target.value)} rows={3}/>:<input type={type} step={type==='number'?'any':undefined} value={payload[key]??''} onChange={e=>change(key,type==='number'?(e.target.value===''?null:Number(e.target.value)):e.target.value)}/>}</label>
 }
 const visible=records.filter(r=>{
  if(r.status==='superseded')return false
  if(filter==='all')return true
  if(['lookahead','daily','weekly'].includes(filter)){
   if(r.kind!=='programme'||r.status==='completed')return false
   const end=filter==='daily'?today:new Date(Date.now()+(filter==='weekly'?7:14)*86400000).toISOString().slice(0,10)
   return r.payload.start_on<=end&&r.payload.finish_on>=today
  }
  return r.kind===filter
 })
 return <main className="pi"><Link href={`/jobs/${jobId}`}>← Back to job</Link><h1>Run this job</h1><p>{data?.job.address??'Loading job…'}</p><p className="muted">Choose a task below. WorkA keeps it with this job and shows you what needs review.</p>
 {error&&<p role="alert" className="pi-alert pi-error">{error} <button onClick={()=>load().catch(e=>setError(e.message))}>Reload records</button></p>}{notice&&<p role="status" className="pi-alert">{notice}</p>}
 <details className="pi-card"><summary>Ask about this job or prepare a change</summary><h2>Ask about this job or prepare a change</h2><label className="pi-field">Job question or site note<textarea value={chat} onChange={e=>setChat(e.target.value)} placeholder="The client is thinking about changing the bathroom tiles from $80 to $300 per square metre. What does that mean for this job?" rows={3}/></label><button disabled={busy||!chat.trim()||!data} onClick={ask}>Prepare a response / draft</button>{reply&&<p className="whitespace-pre-wrap">{reply}</p>}<p className="muted">Suggested fields need review. Save the draft to calculate prices; approve separately to apply changes.</p></details>
 <details className="pi-card"><summary>Add site photos</summary><JobPhotoUpload jobId={jobId} onUploaded={ids=>{void load();start('site_update');setTitle('Site photo update');setPayload({file_ids:ids})}}/></details>
 {!formOpen&&<section className="pi-card"><h2>What would you like to do?</h2><div className="pi-grid">{quickActions.map(([k,label,description])=><button type="button" key={k} disabled={!data||busy} onClick={()=>start(k)} className="text-left p-4"><strong className="block">{label}</strong><span className="block text-sm mt-1">{description}</span></button>)}</div><details className="mt-4"><summary>More job actions</summary><div className="flex flex-wrap gap-2 mt-3">{WORKFLOW_KINDS.filter(k=>!quickActions.some(([q])=>q===k)).map(k=><button type="button" key={k} disabled={!data||busy} onClick={()=>start(k)}>{labels[k]}</button>)}</div></details></section>}
 {formOpen&&<form id="job-record-editor" className="pi-card" onSubmit={e=>{e.preventDefault();void submit('save')}}><h2>{editing?'Edit':'New'} {labels[kind].toLowerCase()}</h2><p className="muted">Save a draft, then review it. Your entry stays here if saving fails.</p>
 <div className="pi-grid">{fields[kind].filter(([key])=>!essentials[kind]||essentials[kind]!.includes(key)).filter(([key])=>!['release_amount','match_reviewed'].includes(key)||!!payload.po_id).filter(([key])=>key!=='po_id'||!!payload.po_id||records.some(r=>r.kind==='purchase_order'&&r.status==='confirmed')).map(field)}</div>
 <details className="my-4"><summary>More details — title, trade and supporting information</summary><label className="pi-field">Title (optional — suggested from your entry)<input maxLength={200} value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="pi-field">Trade<select value={payload.trade_id??''} onChange={e=>change('trade_id',e.target.value?Number(e.target.value):null)}><option value="">Unclassified / not applicable</option>{TRADE_CATEGORIES.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><div className="pi-grid">{fields[kind].filter(([key])=>essentials[kind]&&!essentials[kind]!.includes(key)).map(field)}</div></details>
 <div className="flex flex-wrap gap-2"><button disabled={busy} className="primary">{busy?'Saving…':'Save and review'}</button><button type="button" disabled={busy} onClick={()=>setFormOpen(false)}>Back to job actions</button></div></form>}
 <details className="pi-card"><summary>Find saved job records ({records.filter(r=>r.status!=='superseded').length})</summary> <nav className="pi-tabs" aria-label="Connected job records"><button aria-pressed={filter==='all'} onClick={()=>setFilter('all')}>All records</button><button aria-pressed={filter==='daily'} onClick={()=>setFilter('daily')}>Today / toolbox talk</button><button aria-pressed={filter==='weekly'} onClick={()=>setFilter('weekly')}>Weekly review</button><button aria-pressed={filter==='lookahead'} onClick={()=>setFilter('lookahead')}>Two-week look-ahead</button></nav>
 <label className="pi-field">Show records<select value={WORKFLOW_KINDS.includes(filter as WorkflowKind)?filter:'all'} onChange={e=>setFilter(e.target.value)}><option value="all">All record types</option>{WORKFLOW_KINDS.map(k=><option key={k} value={k}>{labels[k]}</option>)}</select></label>
</details>
 {!visible.length&&data&&<section className="pi-card"><h2>No records here yet</h2><p>Start with a supplier order, a client decision or the next programme activity. Drafts do not change approved financials.</p></section>}
 {visible.map(r=>{const ready=r.kind==='programme'?programmeReadiness(r,records,today):null;return <section className="pi-card" key={r.id} id={r.id}><h2>{r.title}</h2><p>{labels[r.kind]} · {r.status} · Revision {r.version}{r.payload.owner?` · ${r.payload.owner}`:''}{r.payload.due_on?` · Due ${date(r.payload.due_on)}`:''}</p>{r.payload.net_amount!=null&&<p>{currency(r.payload.net_amount)} excluding GST · source {currency(r.payload.source_amount)} {r.payload.tax_basis==='inclusive'?'including':'excluding'} GST</p>}
 {r.kind==='bill'&&<p className="pi-alert">{r.payload.po_id?`Invoice cost ${currency(r.payload.net_amount)} replaces ${currency(r.payload.release_amount??0)} of the outstanding commitment. Difference ${currency((r.payload.net_amount??0)-(r.payload.release_amount??0))}. Review changes before approval.`:'No purchase order matched. Confirm the supplier, job and supporting invoice before recording this cost.'}</p>}
 {r.kind==='trade_quote'&&r.status==='confirmed'&&<p>Claims recorded against this accepted quote: {currency(records.filter(x=>x.kind==='bill'&&x.payload.accepted_quote_id===r.id&&x.status==='confirmed').reduce((sum,x)=>sum+Number(x.payload.net_amount),0))} excluding GST. Compare claimed progress with the quoted scope. <Link href={`/jobs/${jobId}`}>Review estimate pricing</Link>.</p>}
 {ready&&<><p>{date(r.payload.start_on)} – {date(r.payload.finish_on)} · Proposed dates are not confirmed trade bookings.</p><p>{ready.blockers.length?`Waiting on: ${ready.blockers.join(', ')}`:'No linked blockers recorded. Check site readiness before starting.'}</p></>}
 {r.kind==='selection'&&<><dl className="pi-metrics">{[['Supply cost difference',r.result.supply_delta],['Additional expected cost',r.result.expected_cost],['Proposed client charge ex GST',r.result.proposed_charge],['GST',r.result.gst],['Estimated profit if absorbed',r.result.absorbed_profit],['Estimated profit if charged',r.result.charged_profit]].map(([label,value])=><div key={String(label)}><dt>{label}</dt><dd>{currency(value as number|null)}</dd></div>)}</dl><p>{r.result.financial_basis}. Gross profit excludes business overhead. Programme: {r.result.programme_effect}</p><p>Gross margin if absorbed: {r.result.absorbed_margin==null?'Unknown':`${r.result.absorbed_margin}%`} · If charged: {r.result.charged_margin==null?'Unknown':`${r.result.charged_margin}%`}. Markup is applied to cost; margin is profit divided by revenue.</p><details><summary>Matching client email draft</summary><p className="whitespace-pre-wrap">{r.result.email_draft}</p></details></>}
 <details><summary>Review details and evidence</summary>{fields[r.kind].filter(f=>r.payload[f[0]]!=null&&r.payload[f[0]]!=='').map(([key,label])=><p key={key}><strong>{label}: </strong>{Array.isArray(r.payload[key])?r.payload[key].map((id:string)=>records.find(x=>x.id===id)?.title??data.files.find((x:any)=>x.id===id)?.filename??'Unavailable reference').join(', '):String(r.payload[key])}</p>)}</details>
 {r.status==='draft'&&<div className="flex flex-wrap gap-2 mt-3"><button disabled={busy} onClick={()=>start(r.kind,r)}>Review / edit</button><button disabled={busy||(r.kind==='selection'&&!r.result.ready)} className="primary" onClick={()=>submit('confirm',r)}>{r.kind==='selection'?'Prepare variation from reviewed values':r.kind==='purchase_order'?'Approve commitment':r.kind==='bill'?'Confirm bill into job costs':r.kind==='trade_quote'?'Confirm accepted trade quote':'Confirm reviewed record'}</button><button disabled={busy} onClick={()=>submit('supersede',r)}>Withdraw draft</button></div>}
 {r.kind==='trade_quote'&&r.status==='confirmed'&&!r.linked_id&&<details><summary>Incorporate accepted quote into a draft estimate</summary><p>Select exactly the draft items covered by this quote. Their combined cost is replaced by the accepted quote, keeping the previous values in history. Exclusions remain for review.</p><label className="pi-field">Draft estimate<select value={quoteToUse} onChange={e=>{setQuoteToUse(e.target.value);setItemsToReplace([])}}><option value="">Choose a draft</option>{data.drafts?.map((q:any)=><option key={q.id} value={q.id}>Version {q.version}</option>)}</select></label>{data.items?.filter((i:any)=>i.quote_id===quoteToUse&&i.trade_category_id===Number(r.payload.trade_id)&&i.assumption_status!=='excluded').map((i:any)=><label key={i.id} className="pi-check"><input type="checkbox" checked={itemsToReplace.includes(i.id)} onChange={e=>setItemsToReplace(e.target.checked?[...itemsToReplace,i.id]:itemsToReplace.filter(x=>x!==i.id))}/>{i.description} — {currency(i.total)}</label>)}<button disabled={busy||!quoteToUse||!itemsToReplace.length} onClick={()=>applyTrade(r)}>Apply accepted price to selected draft items</button></details>}
 {r.linked_id&&r.kind!=='trade_quote'&&<p><Link href={r.kind==='selection'?`/variations/${r.linked_id}/review`:`/jobs/${jobId}?section=money`}>{r.kind==='selection'?'Open variations for issue and client approval':'View job cost ledger'} →</Link></p>}
 {r.status==='confirmed'&&!['bill','purchase_order','trade_quote','material_transfer'].includes(r.kind)&&<div>{r.kind==='scope_pack'&&<><label className="pi-field">Trade acknowledgement — person, date and evidence<input value={completion[r.id]?.acknowledgement??''} onChange={e=>setCompletion({...completion,[r.id]:{...completion[r.id],acknowledgement:e.target.value}})}/></label><label className="pi-field">Builder release / completion evidence<textarea value={completion[r.id]?.completion_evidence??''} onChange={e=>setCompletion({...completion,[r.id]:{...completion[r.id],completion_evidence:e.target.value}})}/></label></>}<button disabled={busy||!!ready?.blockers.length} onClick={()=>submit('complete',r)}>Confirm complete / resolved</button></div>}
 {r.status==='confirmed'&&['programme','scope_pack','site_update','question','deadline'].includes(r.kind)&&<button disabled={busy} onClick={()=>{start(r.kind);setTitle(r.title);setPayload({...r.payload,replaces_record_id:r.id,replaces_version:r.version})}}>Prepare revised draft</button>}
 {r.kind==='scope_pack'&&<p><a href={`${endpoint}/pack?id=${r.id}`} target="_blank" rel="noreferrer">Open printable scope pack →</a></p>}
 </section>})}
 <p className="muted">Inbox and calendar connections are not configured by this workflow. Record or paste evidence manually. Payment approval and client approval remain separate from a draft.</p>
 </main>
}

