import { getAuthenticatedBuilderId } from '@/lib/auth/api-auth'
import { intelligenceDB } from '@/lib/profitability-data'
export const dynamic='force-dynamic'
const escape=(v:unknown)=>String(v??'Not recorded').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))
export async function GET(req:Request,{params}:{params:{jobId:string}}){
 const builder=await getAuthenticatedBuilderId();if(!builder)return new Response('Sign in required',{status:401})
 const db=intelligenceDB(),id=new URL(req.url).searchParams.get('id')
 const {data:job}=await db.from('jobs').select('id,address').eq('id',params.jobId).eq('builder_id',builder).maybeSingle()
 if(!job)return new Response('Job not found',{status:404})
 const {data:r}=await db.from('job_workflow_records').select('*').eq('id',id).eq('job_id',job.id).eq('builder_id',builder).eq('kind','scope_pack').maybeSingle()
 if(!r)return new Response('Scope pack not found',{status:404})
 const p=r.payload
 const date=(value:unknown)=>typeof value==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(value)?new Date(value+'T12:00:00').toLocaleDateString('en-AU'):'Not recorded'
 const arrangement=({labour_only:'Labour only',supply_install:'Supply and install',split:'Split responsibilities'} as Record<string,string>)[p.arrangement]??'Not confirmed'
 const {data:files,error}=await db.from('files').select('id,filename,drawing_state').eq('job_id',job.id).eq('builder_id',builder).in('id',p.file_ids?.length?p.file_ids:['00000000-0000-0000-0000-000000000000'])
 if(error)return new Response('Attachments unavailable. Please retry.',{status:503})
 const {data:quote}=p.accepted_quote_id?await db.from('job_workflow_records').select('*').eq('id',p.accepted_quote_id).eq('builder_id',builder).eq('job_id',job.id).eq('kind','trade_quote').maybeSingle():{data:null}
 const sections=[['Scope and work areas',p.inclusions],['Exclusions / work by others',p.exclusions],['Supply, protection and access',p.responsibilities],['Issued specification / finish reference',p.specification_ref],['Definition of done',p.finish_standard],['Daily and final clean-up',p.clean_up],['Hold points — builder release required',p.hold_points],['Questions / owner / required by',p.questions||'No questions recorded; verify against issued specifications.'],['Existing agreements / site rules',p.agreements||'No agreement or site rules supplied.'],['Trade acknowledgement',p.acknowledgement||'Not recorded'],['Builder releases and completion evidence',p.completion_evidence||'Not recorded'],['Defects / handover',p.defects||'Not recorded']]
 const html=`<!doctype html><html lang="en-AU"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${escape(r.title)}</title><style>body{font:16px/1.5 system-ui;color:#152c28;max-width:900px;margin:32px auto;padding:0 20px}h1{font-size:28px}h2{font-size:18px;margin-bottom:4px}p{white-space:pre-wrap;margin-top:4px}section{break-inside:avoid}.status{background:#edf4ef;padding:16px}a{color:#145a49}@media print{body{margin:0}.screen{display:none}}</style><p class="screen">Use your browser’s Print / Save as PDF. <a href="/jobs/${escape(job.id)}/workflow#${escape(r.id)}">Back to job record</a></p><h1>${escape(r.title)}</h1><p>${escape(job.address)} · Contact: ${escape(p.owner)}</p><p class="status">${escape(r.status.toUpperCase())} · Reference ${escape(r.id)} · Revision ${r.version}<br>Prepared ${escape(new Date(r.updated_at).toLocaleDateString('en-AU',{timeZone:'Australia/Sydney'}))} · ${p.purpose==='appointed'?'Appointed trade brief':'Request for quote'} · ${escape(arrangement)}<br>Proposed dates: ${escape(date(p.start_on))} to ${escape(date(p.finish_on))}. Bookings and inspections require confirmation.</p>${sections.map(([label,value])=>`<section><h2>${escape(label)}</h2><p>${escape(value)}</p></section>`).join('')}<section><h2>${quote?.status==='confirmed'?'Accepted trade quote':'Trade quote for review'} and qualifications</h2><p>${quote?escape(`${quote.title} (${quote.status}) — ${quote.payload.reference||'Reference not recorded'}\nSupplier: ${quote.payload.supplier}\n${Number(quote.payload.source_amount).toLocaleString('en-AU',{style:'currency',currency:'AUD'})} ${quote.payload.tax_basis==='inclusive'?'including':'excluding'} GST\nInclusions: ${quote.payload.inclusions||'Not recorded'}\nEXCLUSIONS / QUALIFICATIONS: ${quote.payload.exclusions||'Not recorded — review with trade'}`):'No accepted quote linked.'}</p></section><h2>Drawing set and supporting attachments</h2><ul>${(files??[]).map(f=>`<li><a href="/api/jobs/${escape(job.id)}/files/${escape(f.id)}">${escape(f.filename)}</a> — ${escape(f.drawing_state)}</li>`).join('')}</ul><p>Changes require builder approval. This pack records project instructions; it is not a legally reviewed trade agreement.</p></html>`
 return new Response(html,{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'private, no-store','Content-Security-Policy':"default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; frame-ancestors 'none'"}})
}
