// ─── Demo assessment fixture — 16 Alfred Street, Woonona ──────────────────────
// The worked example from the estimating brief, rendered as a ProjectAssessment
// so the reasoning stage is fully demonstrable without Supabase or an API key.
// This is the reference case for the "reason first, price later" pipeline: a
// luxury alts & adds + pool + secondary dwelling at DA maturity, with a
// structural set that only extracts as letterhead.

import type { ProjectAssessment } from './estimation-reasoning'

export const DEMO_ASSESSMENT: ProjectAssessment = {
  job_id: null,
  generated_at: '2026-05-26T00:00:00.000Z',
  demo: true,
  documents: [
    {
      file_id: null,
      filename: 'DA-Mod set (DA.A100–DA.A503).pdf',
      category: 'architectural',
      category_confidence: 98,
      issue_status: 'da_modification',
      document_date: '25/05/26',
      author: 'EMVY',
      extraction_status: 'ok',
      content_summary:
        'Full architectural DA package — site plan, existing base building, proposed ground/first floor plans, roof plan, secondary dwelling, BASIX schedules, elevations, sections, window & door schedule, shadow diagrams, waste plan.',
      unreadable_reason: null,
    },
    {
      file_id: null,
      filename: 'Structurals_16_Alfred_St…S_REV2.pdf',
      category: 'structural',
      category_confidence: 95,
      issue_status: 'unknown',
      document_date: 'REV2',
      author: 'Westlake Punnett & Associates',
      extraction_status: 'failed',
      content_summary:
        'Only letterhead/boilerplate is readable — no footing schedule, beam sizes, slab detail or bracing plan is visible.',
      unreadable_reason:
        'Nominally structural engineering, but the readable content is letterhead only. Treated as present-but-unreadable, not reviewed — footing type, slab design, steel sizing and bracing are all unconfirmed.',
    },
    {
      file_id: null,
      filename: 'Electrical First Draft (CELED).pdf',
      category: 'electrical',
      category_confidence: 96,
      issue_status: 'draft',
      document_date: 'First Draft',
      author: 'CELED (Complete Electrical & LED Lighting)',
      extraction_status: 'partial',
      content_summary:
        'Ground, first floor and secondary dwelling lighting/power layouts with legend — plus six unresolved red-annotated queries still open on the drawings.',
      unreadable_reason: 'Draft only; six RFIs remain open on the drawings (see open questions).',
    },
    {
      file_id: null,
      filename: 'Butlers Pantry Elevations (LJD 4211).pdf',
      category: 'joinery',
      category_confidence: 94,
      issue_status: 'unknown',
      document_date: '10/10/22',
      author: 'Lisa Johnson Design',
      extraction_status: 'ok',
      content_summary: 'Floor plan + 5 elevations for butler’s pantry joinery.',
      unreadable_reason: null,
    },
    {
      file_id: null,
      filename: 'Kitchen Elevation (LJD 4201).pdf',
      category: 'joinery',
      category_confidence: 94,
      issue_status: 'unknown',
      document_date: '10/10/22',
      author: 'Lisa Johnson Design',
      extraction_status: 'ok',
      content_summary: 'Floor plan + 5 elevations for kitchen joinery, incl. island.',
      unreadable_reason: null,
    },
    {
      file_id: null,
      filename: 'DRAFT Fittings+Fixtures+Appliances (LJD).pdf',
      category: 'finishes',
      category_confidence: 92,
      issue_status: 'draft',
      document_date: '13/05/26',
      author: 'Lisa Johnson Design',
      extraction_status: 'partial',
      content_summary:
        'Tapware, sanitaryware, appliances, joinery/door/window hardware, wellness equipment. Schedule total $35,199 but the large majority of rows show "$0.00 Client Total" — not yet selected.',
      unreadable_reason:
        'Option board, not a locked spec — the $35,199 total is not a fit-out budget; most rows are unselected.',
    },
    {
      file_id: null,
      filename: 'DRAFT Materials + Finishes (LJD).pdf',
      category: 'finishes',
      category_confidence: 92,
      issue_status: 'draft',
      document_date: '13/05/26',
      author: 'Lisa Johnson Design',
      extraction_status: 'partial',
      content_summary:
        'Flooring, wall tiles, benchtops, paint/wallpaper, roofing/cladding, fireplaces, drapery — schedule total $0.00, every line is an unselected option.',
      unreadable_reason: 'Every line is an option; none selected. Cannot be read as a finishes budget.',
    },
  ],
  scope: {
    project_type:
      'Alterations & additions to an existing two-storey brick dwelling, with a new detached secondary dwelling (granny flat) and a new in-ground swimming pool.',
    scope_summary: [
      'Demolition of existing garage, laundry, deck/pergola, staircase, chimney and driveway/paths.',
      'Full second-storey addition — 3 bedrooms, study, bathroom, hall, balcony.',
      'Reconfigured ground floor including home theatre, wellness studio, butler’s pantry, mud room, alfresco BBQ kitchen.',
      'New 28,000L in-ground pool with compliant safety fencing and a retractable-sail pergola.',
      'New detached secondary dwelling (bed, bath, kitchenette, lounge), ~42.5m² GFA.',
      'Solar PV, rainwater harvesting (2000L + 3000L), whole-home water filtration.',
      'Luxury architect-and-interior-designer-led fit-out — polished nickel Brodware tapware, Toto smart toilets, stone benchtops, mixed-frame glazing, custom joinery.',
    ],
    site_data: {
      address: '16 Alfred Street, Woonona NSW 2517',
      lot_details: 'Lot 15, Sec M, DP 2697',
      council: 'Wollongong City Council',
      zoning: 'R2',
      site_area_m2: 699.5,
      existing_gfa_m2: 163.2,
      proposed_gfa_m2: 328.9,
      existing_site_coverage: '149.3m² (21.3%)',
      proposed_site_coverage: '283m² (40.4%) — 50% permitted',
      fsr_existing: '0.23:1',
      fsr_proposed: '0.47:1',
      fsr_allowable: '0.5:1',
      storeys: '2 (primary) + 1 (secondary dwelling)',
      building_height: '8.53m primary / 4.89m secondary (9m max allowable)',
      soil_notations: 'Acid sulfate soils Class 5; sloping RLs (36.35–39.92 referenced); heritage N/A',
    },
    room_scope: [
      { level: 'Ground floor', space: 'Existing garage', disposition: 'demolition', notes: 'DA.A104 marks for removal' },
      { level: 'Ground floor', space: 'Freestanding laundry', disposition: 'demolition', notes: 'DA.A104' },
      { level: 'Ground floor', space: 'Timber deck / pergola', disposition: 'demolition', notes: 'DA.A104' },
      { level: 'Ground floor', space: 'Staircase & chimney', disposition: 'demolition', notes: 'DA.A104' },
      { level: 'Ground floor', space: 'Home office', disposition: 'new', notes: null },
      { level: 'Ground floor', space: 'Home theatre (acoustic star-ceiling)', disposition: 'new', notes: 'Specialist acoustic fit-out' },
      { level: 'Ground floor', space: 'Kitchen + butler’s pantry', disposition: 'new', notes: 'LJD joinery (2022-dated — reconcile)' },
      { level: 'Ground floor', space: 'Wellness studio (sauna + ice bath/treadmill provision)', disposition: 'new', notes: 'Specialist' },
      { level: 'Ground floor', space: 'Alfresco BBQ kitchen', disposition: 'new', notes: null },
      { level: 'Ground floor', space: 'Mud room, powder room, foyer, garage', disposition: 'new', notes: null },
      { level: 'First floor', space: 'Bed 1 w/ ensuite & WIR', disposition: 'new', notes: 'Second-storey addition' },
      { level: 'First floor', space: 'Bed 2, Bed 3, study', disposition: 'new', notes: null },
      { level: 'First floor', space: 'Bathroom, hall, balcony', disposition: 'new', notes: null },
      { level: 'Secondary dwelling', space: 'Bedroom, euro laundry, bathroom, kitchenette, lounge, patio', disposition: 'new', notes: 'Detached ~42.5m² — parallel mini-build' },
      { level: 'External', space: 'In-ground pool + safety fencing + retractable-sail pergola', disposition: 'new', notes: '28,000L, AS1926.1 note on DA' },
    ],
    specialty_inclusions: [
      { item: 'In-ground swimming pool (28,000L) + AS1926.1 safety fencing', rationale: 'Own trade — pool construction & compliant fencing', source_ref: 'DA plans (AS1926.1 note)' },
      { item: 'Wellness studio — sauna, ice bath, treadmill provision', rationale: 'Supply-and-install specialist, not standard fit-out', source_ref: 'Ground floor plan' },
      { item: 'Home theatre acoustic star-ceiling', rationale: 'Specialist acoustic panel supply/install', source_ref: 'Ground floor plan' },
      { item: 'Solar PV + battery', rationale: 'Dedicated PV trade; capacity to verify', source_ref: 'Roof plan BASIX clause' },
      { item: 'Whole-home water filtration + rainwater harvesting (2000L + 3000L)', rationale: 'Hydraulic specialist provisional', source_ref: 'DA hydraulic notes' },
      { item: 'Secondary dwelling (granny flat)', rationale: 'Mirrored trade set — footings to kitchenette, priced as a parallel mini-project', source_ref: 'DA.A secondary dwelling sheets' },
    ],
    date_mismatches: [
      'Kitchen & butler’s pantry joinery drawings are dated October 2022 — ~3.5 years before the current DA Modification (May 2026). Layouts must be checked against the current ground floor plan before joinery is priced; the kitchen/butler’s pantry footprint may have shifted during the DA process.',
    ],
    complexity_rating: 'High',
    complexity_justification: [
      'Scale: total GFA doubles 163.2m² → 328.9m² (FSR 0.23:1 → 0.47:1 against a 0.5:1 ceiling) on the same 699.5m² lot.',
      'Five separate Lisa Johnson Design finishes/fixtures/joinery schedules — a documentation tier seen only on interior-designer-led luxury jobs.',
      'Many specialty inclusions each normally its own trade or PS: pool + fencing, sauna/ice bath/treadmill, home theatre acoustic ceiling, smart toilets, solar PV, whole-home filtration, rainwater harvesting.',
      'Site constraints: corner/reserve-adjacent lot, multiple setback lines, sloping RLs (36.35–39.92) and acid sulfate soils Class 5 — standard geotech/civil triggers.',
      'Parallel structure: the detached secondary dwelling roughly doubles small-building trade mobilisations.',
      'Documentation maturity: DA-Modification stage (not IFC), unreadable structural detail, majority-unselected finishes — pushes estimating uncertainty up independent of physical scope.',
    ],
    recommended_estimate_type: 'Budget/Preliminary',
    estimate_type_justification:
      'Not tender-ready because structural/engineering detail is missing or unreadable, no written specification / scope of works was provided and fixtures/finishes are still shown as unselected options. A budget/preliminary estimate is the only responsible output until these are resolved — pricing them firm would embed false precision.',
    trade_list: [
      { trade: 'Demolition', reason: 'Garage, laundry, deck/pergola, staircase and chimney marked for removal', source_ref: 'DA.A104' },
      { trade: 'Structural (concrete, steel, structural carpentry)', reason: 'First-floor addition over existing footprint — needs engineer’s footing/frame detail (currently unreadable)', source_ref: 'Structural REV2 (failed)' },
      { trade: 'Roofing', reason: 'New metal roof (Colorbond Windspray/Gully), 200mm gable rake extensions noted twice', source_ref: 'Roof plan / first floor plan' },
      { trade: 'Windows & doors', reason: '~40 windows and 13 doors across mixed frame/glazing types, each with BASIX U-value/SHGC', source_ref: 'DA.A500/A501' },
      { trade: 'Joinery + stone benchtops', reason: 'Kitchen, butler’s pantry, robes, laundry; benchtop options priced independently', source_ref: 'LJD 4201/4211' },
      { trade: 'Tiling / painting / plastering / architraves', reason: 'Named products per finishes section (Dilorenzo, ABI, Intrim, Porter’s, Dulux)', source_ref: 'Materials + Finishes' },
      { trade: 'Electrical + solar PV', reason: 'Three CELED drawings plus BASIX PV clause', source_ref: 'CELED set / roof plan' },
      { trade: 'Plumbing / hydraulics / gas', reason: 'Rainwater tanks, whole-home filtration, pool equipment, gas BBQ/cooktop/fireplace, HWS', source_ref: 'DA hydraulic notes' },
      { trade: 'Pool construction + safety fencing', reason: 'New 28,000L pool, AS1926.1 compliance note', source_ref: 'DA plans' },
      { trade: 'Specialist wellness / home theatre', reason: 'Sauna, ice bath, treadmill, acoustic star-ceiling — supply & install', source_ref: 'Ground floor plan' },
      { trade: 'Secondary dwelling (mirrored trade set)', reason: 'Footings → kitchenette, priced as a parallel mini-project', source_ref: 'DA.A secondary dwelling' },
      { trade: 'External works / landscaping / fencing', reason: 'Sandstone/limestone paving, retaining, boundary & pool fencing, letterbox', source_ref: 'Materials + Finishes' },
      { trade: 'Preliminaries, contingency, margin', reason: 'Standard for the scale; contingency at the higher end given documentation gaps', source_ref: 'Whole project' },
    ],
    assumptions: [
      'The DA Modification set represents current, agreed design intent for the architectural envelope.',
      'The two LJD schedules represent the palette under consideration, not a locked specification.',
      'No conflict exists between the DA plans and the 2022-dated joinery drawings until checked.',
    ],
    risks: [
      'Structural engineering content is not readable — footing type, slab design, steel sizing and bracing are unconfirmed.',
      'DA-Modification stage — marked "DO NOT USE FOR CONSTRUCTION"; not IFC/CC.',
      'Roof plan "SOLAR 10KW" ×6 appears inconsistent with the BASIX 2.6 peak kW minimum — verify, do not assume either way.',
      'No geotech, survey, civil/stormwater or landscape package supplied despite sloping RLs and acid sulfate soils.',
      'No written specification / scope of works provided.',
      'Existing dwelling age/construction unstated — hazmat (asbestos) survey a standard risk until confirmed.',
      'Six electrical RFIs remain open on the CELED drawings.',
      'Schedule totals ($35,199 and $0.00) must NOT be read as fit-out budgets — both are overwhelmingly unselected options.',
    ],
    exclusions: [
      'Council conditions of consent (not yet issued on this evidence).',
      'Pool heating/mechanical selection.',
      'Final PV system size.',
      'Final fireplace type (flued vs flueless — both still shown as options).',
      'Final benchtop material.',
    ],
  },
  open_questions: [
    { group: 'missing_documents', question: 'Readable structural engineering drawings — footing schedule, slab design, steel sizes, bracing. Currently only letterhead is visible.', source_reference: 'Structurals REV2' },
    { group: 'missing_documents', question: 'Written specification / scope of works — drawings show what, not to what standard.', source_reference: null },
    { group: 'missing_documents', question: 'Geotechnical report — sloping RLs and Class 5 acid sulfate soils affect footings/earthworks.', source_reference: null },
    { group: 'missing_documents', question: 'Land survey to confirm levels/boundaries for excavation and retaining.', source_reference: null },
    { group: 'missing_documents', question: 'Civil/stormwater design — pool, tanks and increased coverage typically require a stormwater plan.', source_reference: null },
    { group: 'missing_documents', question: 'Landscape design package — DA shows planters/paving in concept only.', source_reference: null },
    { group: 'missing_documents', question: 'Council conditions of consent once the DA Modification is determined.', source_reference: null },
    { group: 'drawing_annotations', question: 'Pendant vs wall light at bed sides — first floor.', source_reference: 'CELED first floor' },
    { group: 'drawing_annotations', question: 'Sub-board location for the secondary dwelling — recessed / set into board?', source_reference: 'CELED secondary dwelling' },
    { group: 'drawing_annotations', question: 'Two-way switching for path/garden lighting to the house — secondary dwelling?', source_reference: 'CELED secondary dwelling' },
    { group: 'drawing_annotations', question: 'Downlights vs wall lights for the ground floor hall.', source_reference: 'CELED ground floor' },
    { group: 'drawing_annotations', question: 'Festoon lighting switched GPO layout/locations — ground floor.', source_reference: 'CELED ground floor' },
    { group: 'drawing_annotations', question: 'Front yard spike light allowance — scope/quantity to confirm.', source_reference: 'CELED' },
    { group: 'unselected_finishes', question: 'Fireplace type — flued Ortal vs flueless Jetmaster?', source_reference: 'Materials + Finishes' },
    { group: 'unselected_finishes', question: 'Benchtop material — Corian / quartzite / porcelain?', source_reference: 'Materials + Finishes' },
    { group: 'unselected_finishes', question: 'Floor tile per wet area, wall paint colours per room, carpet vs timber upstairs.', source_reference: 'Materials + Finishes' },
    { group: 'unselected_finishes', question: 'BBQ / rangehood combination — several mutually exclusive options listed for the same location.', source_reference: 'Fittings + Fixtures' },
    { group: 'commercial', question: 'Builder’s margin / overheads & profit % to gross up trade totals.', source_reference: null },
    { group: 'commercial', question: 'Preliminaries basis — program duration, supervision, owner living on site during works?', source_reference: null },
    { group: 'commercial', question: 'Contract type — lump sum, cost-plus, or construction management?', source_reference: null },
    { group: 'commercial', question: 'Region/labour basis — Illawarra/Wollongong rates vs another benchmark?', source_reference: null },
    { group: 'commercial', question: 'GST treatment — figures ex-GST or inc-GST for the intended audience?', source_reference: null },
    { group: 'commercial', question: 'Is the secondary dwelling the same contract as the primary works, or a separate build?', source_reference: null },
    { group: 'output', question: 'Confirm estimate type — Budget (recommended), Tender, or Internal Costing.', source_reference: null },
    { group: 'output', question: 'File format(s) — Excel workbook, PDF, and/or client-facing quotation?', source_reference: null },
  ],
}
