import { money, quantity, quotePackages, round, totals } from './project-studio.ts'
import type { Revision } from './project-studio.ts'

const escape = (text: string) => text.replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))

/** Portable client document: no scripts, external fonts, remote assets or builder margins. */
export function summaryHtml(revision: Revision, accepted: boolean) {
  const t=totals(revision), w=revision.design.width
  const packages=quotePackages(revision)
  return '<!doctype html><html lang="en-AU"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Gumtree House — Client summary</title><style>'+
    '@page{size:A4;margin:16mm}*{box-sizing:border-box}body{font:14px/1.65 Arial,sans-serif;color:#263f34;background:#f4f5ef;margin:0;padding:35px}main{max-width:850px;margin:auto;background:#fffefa;padding:45px}header{display:flex;justify-content:space-between;border-bottom:1px solid #dbe1d3;padding-bottom:20px}header b{font-size:32px}h1{font-size:32px;margin-bottom:4px}h2{font-size:17px;margin-top:25px}p{color:#687661}small{display:block;font-size:11px}.meta{background:#edf1e6;padding:12px;font-size:12px}table{width:100%;border-collapse:collapse;font-size:12px}td,th{padding:13px 8px;border-bottom:1px solid #dce1d4;text-align:left;vertical-align:top}td:last-child,th:last-child{text-align:right;white-space:nowrap}tr{break-inside:avoid}.totals{margin:20px 0 25px auto;max-width:310px}.totals div{display:flex;justify-content:space-between;padding:6px}.totals div:last-child{font-size:17px;border-top:1px solid #cdd8c4}footer{font-size:10px;border-top:1px solid #dce1d4;margin-top:25px;padding-top:15px}.plan{display:block;width:100%;max-width:470px;margin:20px auto;max-height:230px}@media print{body{background:white;padding:0}main{padding:0;max-width:none}h2{break-after:avoid}.totals,header,.plan{break-inside:avoid}}'+
    '</style></head><body><main><header><b>worka.</b><div>GUMTREE BUILDING CO.<small>Fictional demonstration builder</small></div></header><p>CLIENT PROJECT SUMMARY · DEMONSTRATION ONLY</p><h1>Gumtree House</h1><p>Kitchen, living &amp; dining extension · Blue Mountains, NSW</p><div class="meta">GH–026 / R'+revision.id+' · '+(accepted?'Accepted demo scope':'Working proposal · not approved')+'</div><h2>Your proposed space</h2><p>'+w.toFixed(1)+' × 6.0 m external footprint · '+round(w*6).toFixed(1)+' m² · 2.7 m wall height.</p>'+
    '<svg class="plan" xmlns="http://www.w3.org/2000/svg" viewBox="-35 -25 '+(w*40+80)+' 300" role="img" aria-label="Conceptual floor plan"><rect width="'+w*40+'" height="240" fill="#e8dfc8" stroke="#47694e" stroke-width="5"/><path d="M'+w*20+' 0V240M'+w*20+' 100H'+w*40+'" fill="none" stroke="#b9b99e" stroke-dasharray="4 5"/><g font-family="Arial" font-size="12" text-anchor="middle" fill="#36513b"><text x="'+w*10+'" y="120">Living</text><text x="'+w*30+'" y="55">Kitchen</text><text x="'+w*30+'" y="175">Dining</text><text x="'+w*20+'" y="266">'+w.toFixed(1)+' m</text><text x="'+(w*40+25)+'" y="125" transform="rotate(90 '+(w*40+25)+' 125)">6.0 m</text></g></svg><small>Concept zones only. Dashed lines show zones, not walls. Not a construction drawing.</small>'+
    '<h2>Included scope</h2><table><thead><tr><th>Work package</th><th>Quantities</th><th>Price ex GST</th></tr></thead><tbody>'+
    packages.map(p=>'<tr><td><b>'+escape(p.trade)+'</b>'+p.lines.map(l=>'<small>'+escape(l.name)+(l.allowance?' (allowance)':'')+'</small>').join('')+'</td><td>'+p.lines.map(l=>'<small>'+quantity(l,revision.design)+' '+escape(l.unit)+'</small>').join('')+'</td><td>'+money(p.price)+'</td></tr>').join('')+
    '</tbody></table><div class="totals"><div><span>Total ex GST</span><b>'+money(t.price)+'</b></div><div><span>GST (10%)</span><b>'+money(t.gst)+'</b></div><div><span>Total incl GST</span><b>'+money(t.total)+'</b></div></div><h2>Scope &amp; assumptions</h2><p>Concept dimensions and illustrative sample rates. Gross footprint and perimeter are estimating proxies. Allowances are included and subject to selection and verification. No drawing extraction, engineering or compliance assessment has been performed.</p><h2>Exclusions</h2><p>'+escape(revision.exclusions)+'</p>'+
    (revision.lines.some(l=>!l.included)?'<p>Excluded estimate items: '+revision.lines.filter(l=>!l.included).map(l=>escape(l.name)).join('; ')+'.</p>':'')+
    '<footer>Prepared for discussion. Fictional project, not an offer or construction contract. Demo acceptance and variations do not constitute client authorisation. All figures AUD. Use your browser’s Print command to save this document as PDF.</footer></main></body></html>'
}
