import test from 'node:test'
import assert from 'node:assert/strict'
import { acceptEstimate, acceptedRevision, approveVariation, createDemoProject, draftVariation, financials, lineCost, parseProject, paymentSchedule, quantity, quotePackages, revise, round, totals, variationDelta } from './project-studio.ts'
import { summaryHtml } from './project-studio-export.ts'

test('base estimate independently reconciles cost, markup, GST and margin', () => {
  const p=createDemoProject(), t=totals(p.working)
  assert.equal(t.cost, 6500+48*340+48*280+48*170+28*460+12500+48*220+18000+11000)
  assert.equal(t.cost,109360)
  assert.equal(t.price,136700)
  assert.equal(t.gst,13670)
  assert.equal(t.total,150370)
  assert.equal(t.margin,20)
})
test('widening geometry changes measured packages but not fixed allowances', () => {
  const p=createDemoProject(), wider=revise(p,{design:{...p.working.design,width:9}})
  assert.equal(quantity(wider.working.lines[1],wider.working.design),54)
  assert.equal(quantity(wider.working.lines[4],wider.working.design),30)
  assert.equal(totals(wider.working).cost-totals(p.working).cost,6*(340+280+170+220)+2*460)
  assert.equal(totals(wider.working).price-totals(p.working).price,8725)
  assert.equal(lineCost(wider.working.lines[5],wider.working.design),12500)
})
test('acceptance captures an immutable baseline and drafts do not change finances', () => {
  let p=acceptEstimate(createDemoProject())
  const baseline=JSON.stringify(p.baseline), before=financials(p)
  p=revise(p,{design:{...p.working.design,width:9}})
  p=draftVariation(p)
  assert.deepEqual(financials(p),before)
  assert.equal(JSON.stringify(p.baseline),baseline)
  assert.equal(acceptedRevision(p)?.design.width,8)
  assert.equal(variationDelta(p.variations[0]).price,8725)
})
test('approval applies once and preserves the baseline', () => {
  let p=acceptEstimate(createDemoProject())
  p=draftVariation(revise(p,{design:{...p.working.design,width:9}}))
  p=approveVariation(p,'VAR-001')
  const f=financials(p)
  assert.equal(f.revenue,145425)
  assert.equal(f.baseline,109360)
  assert.equal(f.budget,116340)
  assert.equal(f.profit,29085)
  assert.deepEqual(approveVariation(p,'VAR-001'),p)
  assert.equal(acceptEstimate(p),p)
})
test('stale drafts cannot be approved and refresh captures latest revision', () => {
  let p=acceptEstimate(createDemoProject())
  p=draftVariation(revise(p,{design:{...p.working.design,width:9}}))
  p=revise(p,{markup:30})
  assert.equal(approveVariation(p,'VAR-001'),p)
  p=approveVariation(draftVariation(p),'VAR-001')
  assert.equal(financials(p).revenue,151242)
  assert.equal(p.variations.length,1)
})
test('multiple approvals and negative variations reconcile without double application', () => {
  let p=acceptEstimate(createDemoProject())
  p=approveVariation(draftVariation(revise(p,{design:{...p.working.design,width:9}})),'VAR-001')
  p=draftVariation(revise(p,{design:{...p.working.design,width:8}}))
  assert.equal(variationDelta(p.variations[1]).price,-8725)
  p=approveVariation(p,'VAR-002')
  assert.equal(financials(p).revenue,136700)
  assert.equal(financials(p).baseline,109360)
  assert.equal(p.variations.filter(v=>v.status==='approved').length,2)
})
test('actuals consume commitments; overruns reduce profit without duplicate costs', () => {
  let p=acceptEstimate(createDemoProject())
  p={...p,costs:p.costs.map(c=>c.trade==='Structure'?{...c,committed:35000,actual:10000}:c)}
  let f=financials(p), structure=f.rows.find(r=>r.trade==='Structure')!
  assert.equal(structure.forecast,35000)
  assert.equal(structure.remainingCommitted,25000)
  assert.equal(structure.uncommitted,0)
  assert.equal(f.forecast,114600)
  assert.equal(f.profit,22100)
  p={...p,costs:p.costs.map(c=>c.trade==='Structure'?{...c,actual:40000}:c)}
  f=financials(p)
  assert.equal(f.rows.find(r=>r.trade==='Structure')!.forecast,40000)
  assert.equal(f.forecast,round(f.actual+f.remainingCommitted+f.uncommitted))
})
test('exclusions, decimal rates and zero markup calculate correctly', () => {
  let p=createDemoProject()
  p=revise(p,{markup:0,lines:p.working.lines.map(l=>l.id==='glazing'?{...l,included:false}:l.id==='site'?{...l,rate:6500.17}:l)})
  assert.equal(totals(p.working).cost,96860.17)
  assert.equal(totals(p.working).profit,0)
  assert.equal(totals(p.working).total,106546.19)
})
test('payment allocations reconcile to cents and receipts do not change forecast', () => {
  let p=acceptEstimate(revise(createDemoProject(),{markup:23.17}))
  const rows=paymentSchedule(p), f=financials(p)
  assert.equal(round(rows.reduce((s,r)=>s+r.amount,0)),f.revenue)
  assert.equal(round(rows.reduce((s,r)=>s+r.cost,0)),f.forecast)
  assert.equal(rows.at(-1)!.cumulative,f.profit)
  p={...p,receipts:[5000,0,0,0,0,0]}
  assert.deepEqual(financials(p),f)
  assert.equal(paymentSchedule(p)[0].received,5000)
})
test('backup roundtrip preserves approved history; rejects malformed data', () => {
  let p=acceptEstimate(createDemoProject())
  p=approveVariation(draftVariation(revise(p,{design:{...p.working.design,width:9}})),'VAR-001')
  assert.deepEqual(parseProject(JSON.stringify(p)),p)
  assert.equal(parseProject('not json'),null)
  assert.equal(parseProject(JSON.stringify({...p,id:'production'})),null)
  assert.equal(parseProject(JSON.stringify({...p,costs:[]})),null)
  assert.equal(parseProject(JSON.stringify({...p,working:{...p.working,markup:-2}})),null)
  assert.equal(parseProject(JSON.stringify({...p,variations:[...p.variations,...p.variations]})),null)
})
test('client package prices reconcile exactly even with fractional cents in markup', () => {
  const p=revise(createDemoProject(),{markup:23.17,lines:createDemoProject().working.lines.map(l=>({...l,rate:l.rate+0.13}))})
  assert.equal(round(quotePackages(p.working).reduce((s,p)=>s+p.price,0)),totals(p.working).price)
})
test('portable summary escapes user text and includes only client selling prices', () => {
  const p=revise(createDemoProject(),{exclusions:'<script>alert("unsafe")</script>'})
  const html=summaryHtml(p.working,false)
  assert.ok(html.includes('Working proposal · not approved'))
  assert.ok(html.includes('$150,370.00'))
  assert.ok(html.includes('&lt;script&gt;'))
  assert.ok(!html.includes('<script>'))
  assert.ok(!html.includes('$109,360.00'))
  assert.ok(!html.includes('gross profit'))
  assert.ok(html.includes('Conceptual floor plan'))
})
