import test from 'node:test'
import assert from 'node:assert/strict'
import {createBudgetPlan,budgetPreview,applyBudget} from './studio-budget.ts'
import {newWorkspace,parseWorkspace} from './studio-workspace.ts'
import {totals} from './project-studio.ts'
import {rectangleGeometry} from './studio-geometry.ts'

function fixture(){const w=newWorkspace();w.project.working.markup=20;w.project.working.design={width:8,depth:6,height:2.7,geometry:rectangleGeometry(8,6,2.7)};w.project.working.design.geometry!.rooms=[{id:'dry',name:'Bedroom',finish:'oak',furniture:'bedroom',polygon:[{x:0,y:0},{x:4,y:0},{x:4,y:3},{x:0,y:3}]},{id:'wet',name:'Bathroom',finish:'oak',furniture:'none',polygon:[{x:4,y:0},{x:8,y:0},{x:8,y:3},{x:4,y:3}]}];w.project.working.lines=[{id:'joinery',name:'Kitchen joinery',trade:'Interiors',source:'entered',quantity:1,unit:'item',rate:20000,included:true,allowance:true,note:''},{id:'floor',name:'Floor finishes and stairs',trade:'Interiors',source:'entered',quantity:1,unit:'item',rate:10000,included:true,allowance:true,note:''},{id:'structure',name:'Structural cabinetry',trade:'Structure',source:'entered',quantity:1,unit:'item',rate:50000,included:true,allowance:true,note:''},{id:'omitted',name:'Island cabinetry',trade:'Interiors',source:'entered',quantity:1,unit:'item',rate:8000,included:false,allowance:true,note:''}];return w}
test('budget uses real totals, associated costs, GST and protected priority',()=>{const w=fixture(),p=createBudgetPlan(w.project.working);assert.equal(p.choices.length,2);p.target=0;p.choices[0].priority='keep';p.choices[1].replacement=8000;p.choices[1].extra=500;const v=budgetPreview(p);assert.equal(v.saving,1980);assert.equal(v.after.profit,15700);assert.equal(v.after.margin,v.original.margin);assert.equal(v.selected.length,1);assert.equal(totals(w.project.working).cost,80000);assert.equal(v.revision.lines.find(l=>l.id==='omitted')!.included,false)})
test('budget cannot remove protected work or apply invalid replacement values',()=>{const p=createBudgetPlan(fixture().project.working);p.target=0;p.choices[0].lineId='structure';p.choices[1].replacement=-1;assert.equal(budgetPreview(p).selected.length,0);p.choices[1].replacement=0;assert.equal(budgetPreview(p).selected.length,0);p.choices[1].lineId='missing';assert.doesNotThrow(()=>budgetPreview(p))})
test('below-target proposals select nothing; insufficient savings retain a gap',()=>{const p=createBudgetPlan(fixture().project.working);p.target=1e6;assert.equal(budgetPreview(p).saving,0);p.target=1;assert.ok(budgetPreview(p).gap>0);assert.equal(budgetPreview(p).selected.length,2)})
test('finish preview changes selected dry room only without changing geometry',()=>{const p=createBudgetPlan(fixture().project.working);p.target=0;p.choices[1].floorRooms=['dry','wet'];const v=budgetPreview(p);assert.equal(v.revision.design.geometry!.rooms![0].finish,'carpet');assert.equal(v.revision.design.geometry!.rooms![1].finish,'oak');assert.deepEqual(v.revision.design.geometry!.walls,p.base.design.geometry!.walls);assert.equal(p.base.design.geometry!.rooms![0].finish,'oak')})
test('apply retains contract and original option, round-trips and cannot compound savings',()=>{const w=fixture(),p=createBudgetPlan(w.project.working);p.target=0;w.project.baseline=structuredClone(w.project.working);w.budget=p;assert.ok(parseWorkspace(w));const next=applyBudget(w,p,'balanced');assert.deepEqual(next.project.baseline,w.project.baseline);assert.deepEqual(next.options[0].revision,w.project.working);assert.equal(next.options.length,2);assert.equal(next.project.working.id,w.project.working.id+1);assert.ok(parseWorkspace(next));assert.equal(createBudgetPlan(next.project.working).choices.length,0);assert.throws(()=>applyBudget(next,p,'balanced'),/Estimate changed/);w.options=Array.from({length:11},(_,i)=>({id:String(i),name:'Option',savedAt:new Date().toISOString(),revision:w.project.working}));assert.throws(()=>applyBudget(w,p,'balanced'),/two free/);p.target=NaN;assert.equal(parseWorkspace(w),null)})
test('review flag requires reference and unreviewed replacement loses verified rate',()=>{const p=createBudgetPlan(fixture().project.working);p.target=0;p.choices[0].reviewed=true;let v=budgetPreview(p);assert.equal(v.revision.lines[0].rateVerified,false);p.choices[0].reference='Builder allowance review';v=budgetPreview(p);assert.equal(v.revision.lines[0].rateVerified,true);assert.equal(v.provisional,true)})
