import {test} from 'node:test'
import assert from 'node:assert/strict'
import {newWorkspace,parseWorkspace} from './studio-workspace.ts'
import {applyBuilderEstimate,builderCostSummary} from './studio-builder-estimate.ts'
import {newScopeReview} from './studio-scope.ts'
const item=(name='Kitchen cabinetry')=>({scope:'joinery',name,unit:'item',quantity:1,quantityBasis:'assumed',material:32000,labour:0,estimateType:'PC',basis:'Assumed mid-range cabinetry supply; installation excluded. Confirm selections.'})
const response=()=>({groups:[],items:[item(),{...item('Laundry cabinetry'),material:5500}],summary:'Alterations with kitchen and laundry allowances.',assumptions:['Mid-range finishes assumed.'],exclusions:['Loose furniture.'],warnings:['Engineering not supplied.'],contingencyPercent:5,options:[{name:'Upgrade cabinetry',cost:3000,basis:'Incremental supply allowance.'}]})
test('plan-only empty scope can become detailed cost items, including several items in one category',()=>{const w=newWorkspace(),before=JSON.stringify(w),next=applyBuilderEstimate(w,response());assert.equal(next.project.working.lines.length,2);assert.equal(next.project.working.lines[0].rateVerified,false);assert.equal(next.project.working.lines[0].quantityVerified,false);assert.equal(next.project.working.lines[0].estimateType,'PC');assert.ok(parseWorkspace(next));assert.equal(JSON.stringify(w),before);assert.deepEqual(next.project.baseline,w.project.baseline);assert.deepEqual(next.project.costs,w.project.costs);assert.equal(builderCostSummary(next).cost,37500);assert.equal(builderCostSummary(next).reserve,1875);assert.equal(builderCostSummary(next).costWithReserve,39375)})
test('adding missing work in a partially covered category preserves existing prices',()=>{const w=applyBuilderEstimate(newWorkspace(),{...response(),items:[item()]});const next=applyBuilderEstimate(w,{...response(),items:[item('Laundry cabinetry')]});assert.equal(next.project.working.lines[0].rate,32000);assert.equal(next.project.working.lines.length,2);assert.deepEqual(next.project.baseline,w.project.baseline)})
test('refresh rejects duplicated items, excluded categories and invalid amounts atomically',()=>{const w=applyBuilderEstimate(newWorkspace(),response()),before=JSON.stringify(w);assert.throws(()=>applyBuilderEstimate(w,response()));assert.equal(JSON.stringify(w),before);const excluded=newWorkspace();excluded.scopeReview=newScopeReview();excluded.scopeReview.items.find(i=>i.key==='joinery')!.status='excluded';assert.throws(()=>applyBuilderEstimate(excluded,response()));for(const value of [Infinity,NaN,-1,1e8])assert.throws(()=>applyBuilderEstimate(newWorkspace(),{...response(),items:[{...item(),material:value}]}));assert.throws(()=>applyBuilderEstimate(newWorkspace(),{...response(),contingencyPercent:31}))})
test('assumptions, PC/PS and options survive save roundtrip; options are excluded from base cost',()=>{const next=applyBuilderEstimate(newWorkspace(),response()),saved=parseWorkspace(JSON.stringify(next));assert.ok(saved);assert.deepEqual(saved.builderReview,next.builderReview);assert.equal(builderCostSummary(saved).cost,37500);saved.project.working.lines[0].quantity=2;assert.equal(builderCostSummary(saved).reserve,3475);assert.equal(parseWorkspace({...saved,builderReview:{...saved.builderReview,options:[{name:'Bad',cost:Infinity,basis:'Invalid'}]}}),null)})
test('zero priced group output cannot skip existing unpriced included work',()=>{const w=newWorkspace();w.project.working.lines=[{id:'a',trade:'Structure',name:'Structural beam',unit:'item',quantity:1,source:'entered',rate:0,included:true,allowance:true,note:'Engineer to confirm.'}];assert.throws(()=>applyBuilderEstimate(w,response()));const next=applyBuilderEstimate(w,{...response(),groups:[{id:'group-0',unit:'item',material:5000,labour:2000,basis:'Provisional supply and installation.'}]});assert.equal(next.project.working.lines[0].rate,5000)})
