import test from 'node:test'
import assert from 'node:assert/strict'
import {drawingSetInput} from './studio-api-input.ts'
import {recognisedSet} from './studio-set-recognition.ts'
import {renderInput,renderImage,renderedImage} from './studio-image-api.ts'
import {querySite,screeningChecks,validSiteReport,siteLocation,planningBase,terrainBase} from './studio-site.ts'
import {newWorkspace,parseWorkspace,clientProjection} from './studio-workspace.ts'
const points=[{x:100,y:100},{x:900,y:100},{x:900,y:700},{x:100,y:700}]
const plan=()=>({kind:'floor-plan',dimension:{a:points[0],b:points[1],metres:8},footprint:points,walls:points.map((a,i)=>({name:'Wall '+i,a,b:points[(i+1)%4],height:2.7,thickness:.15,openings:[]})),rooms:[],dimensions:[],warnings:[]})
const pages=[0,1,2].map(i=>({image:'data:image/png;base64,YQ==',name:'Drawing set',page:i+1,aspect:1.25,metresPerUnit:0}))
const set=()=>({warnings:['Check alignment against sections.'],floors:[{name:'Ground',pageIndex:0,elevation:0,offsetX:0,offsetY:0,alignmentEvidence:'Common wall axis A',plan:plan()},{name:'First',pageIndex:1,elevation:3,offsetX:2,offsetY:1,alignmentEvidence:'Section S1',plan:plan()}]})
test('joint reconstruction aligns independent pages and preserves audit warnings in storage',()=>{
 const r=recognisedSet(set(),pages);assert.equal(r.geometry.storeys?.[0].geometry.footprint[0].x,2);assert.equal(r.geometry.storeys?.[0].elevation,3);assert.ok(r.warnings.some(s=>s.includes('unmodelled')));assert.equal(r.geometry.verified,false)
 const w=newWorkspace();w.project.working.design=r.design;w.setReview={at:new Date().toISOString(),warnings:r.warnings};assert.ok(parseWorkspace(w));assert.equal(JSON.stringify(clientProjection(w)).includes('Common wall axis A'),false)
})
test('joint reconstruction rejects repeated floors, absent scale and ambiguous elevations',()=>{const v=set();v.floors[1].pageIndex=0;assert.throws(()=>recognisedSet(v,pages));const a=set();a.floors[1].elevation=0;assert.throws(()=>recognisedSet(a,pages),/distinct elevations/);const b=set();(b.floors[1].plan as any).dimension=null;assert.throws(()=>recognisedSet(b,pages),/No readable dimension/)})
test('drawing inputs enforce request bounds and reject arbitrary image URLs',()=>{assert.equal(drawingSetInput(pages).length,3);assert.throws(()=>drawingSetInput([...pages,pages[0]]),/repeated/);assert.throws(()=>drawingSetInput([{...pages[0],image:'http://localhost/private'}]));assert.throws(()=>drawingSetInput(Array(9).fill(pages[0])))})
function png(){const b=Buffer.alloc(24);Buffer.from('89504e470d0a1a0a','hex').copy(b);b.writeUInt32BE(1024,16);b.writeUInt32BE(768,20);return 'data:image/png;base64,'+b.toString('base64')}
test('image adapter sends reference pixels to the fixed provider endpoint and meters output',async()=>{let called=false;const result=await renderImage('test-key',renderInput({image:png(),style:'warm timber',title:'Test'}),new AbortController().signal,(async(url,init)=>{called=true;assert.equal(url,'https://api.openai.com/v1/images/edits');assert.equal((init?.headers as any).Authorization,'Bearer test-key');const form=init?.body as FormData;assert.ok(form.get('image') instanceof Blob);assert.match(String(form.get('prompt')),/Preserve the supplied camera/);assert.equal(form.get('n'),'1');return new Response(JSON.stringify({usage:{input_tokens:20,output_tokens:30},data:[{b64_json:'iVBORw0KGgo='}]}),{headers:{'x-request-id':'test'}})}) as typeof fetch);assert.ok(called);assert.equal(result.usage.output_tokens,30);assert.equal(renderedImage(result.image),'data:image/png;base64,iVBORw0KGgo=');assert.throws(()=>renderInput({image:'data:image/png;base64,YQ==',style:'',title:''}));assert.throws(()=>renderedImage('https://example.com/image.png'))})
test('image provider failures do not expose provider bodies or credentials',async()=>{await assert.rejects(()=>renderImage('secret',renderInput({image:png(),style:'',title:''}),new AbortController().signal,(async()=>new Response(JSON.stringify({error:{message:'private drawing text secret'}}),{status:401})) as typeof fetch),e=>e instanceof Error&&!e.message.includes('secret')&&!e.message.includes('private')&&e.message.includes('rejected'))})
test('spatial failures and transfer-limit truncation remain unresolved',async()=>{const r=await querySite({latitude:-33.86,longitude:151.21},(async()=>new Response(JSON.stringify({features:[],exceededTransferLimit:true}))) as typeof fetch);assert.ok(r.layers.every(l=>l.status==='unavailable'));assert.equal(r.terrainStatus,'unavailable');assert.ok(screeningChecks(r,8,100,500).every(c=>c.result.startsWith('Unresolved')));assert.ok(validSiteReport(r));assert.throws(()=>siteLocation({latitude:0,longitude:0}))})
test('conflicting controls cannot yield a passing planning check; site evidence stays private',async()=>{const r=await querySite({latitude:-33.86,longitude:151.21},(async()=>new Response(JSON.stringify({features:[]}))) as typeof fetch);r.layers.find(l=>l.name==='Building height')!.status='found';r.layers.find(l=>l.name==='Building height')!.features=[{MAX_B_H_M:8.5},{MAX_B_H_M:12}];assert.match(screeningChecks(r,8,100,500)[0].result,/Unresolved/);const w=newWorkspace();w.siteReport=r;assert.ok(parseWorkspace(w));assert.equal(JSON.stringify(clientProjection(w)).includes(planningBase),false);r.terrainSource='https://untrusted.example';assert.equal(validSiteReport(r),false)})
