import {test} from 'node:test'
import assert from 'node:assert/strict'
import {newWorkspace,parseWorkspace,recordApproval,clientProjection,approvalIssues} from './studio-workspace.ts'
import {rectangleGeometry,resizeLevel,buildingDimensions} from './studio-geometry.ts'
import {packageLines,changeImpact,impactTopics,scopeSignature} from './studio-change.ts'
import {revise,financials,draftVariation} from './project-studio.ts'
function fixture(){const w=newWorkspace();const geometry=rectangleGeometry(8,6,2.7);geometry.verified=true;w.project.working.design=buildingDimensions(geometry);let id=0;w.project.working.lines=packageLines('wall',geometry.walls[0].id,'North wall',()=>String(++id)).map(l=>({...l,rate:10,labour:5,rateVerified:true}));return w}
test('wall package keeps every component linked; area changes update all costs',()=>{const w=fixture(),a=w.project.working,b={...a,design:buildingDimensions(resizeLevel(a.design.geometry!,1.25,1))};const d=changeImpact(a,b);assert.equal(d.rows.length,4);assert.ok(d.rows.every(r=>r.after>r.before));assert.ok(d.totalDelta>0);assert.ok(parseWorkspace(w))})
test('removed scope is a negative cost impact and markup-only change remains visible',()=>{const a=fixture().project.working;const d=changeImpact(a,{...a,lines:[]});assert.equal(d.rows.length,4);assert.ok(d.rows.every(r=>r.status==='Removed'&&r.costDelta<0));const m=changeImpact(a,{...a,markup:50});assert.equal(m.rows.length,0);assert.equal(m.markupChanged,true);assert.ok(m.totalDelta>0)})
test('geometry variation requires current impact evidence; later rate changes invalidate evidence',()=>{let w=recordApproval(fixture(),'Synthetic client','Test evidence');const agreed=financials(w.project).revenue;const geometry=resizeLevel(w.project.working.design.geometry!,1.25,1);geometry.verified=true;w.project=revise(w.project,{design:buildingDimensions(geometry)});w.project=draftVariation(w.project);assert.throws(()=>recordApproval(w,'Synthetic client','Test','VAR-001'),/Review change impact/);const signature=scopeSignature(w.project.working);w.project=revise(w.project,{impactReview:impactTopics.map(topic=>({topic,status:'included',note:'Covered by priced test items',signature}))});assert.deepEqual(approvalIssues(w),[]);assert.equal(financials(w.project).revenue,agreed);assert.ok(parseWorkspace(w));const publicData=JSON.stringify(clientProjection(w));assert.ok(!publicData.includes('costDelta'));assert.ok(!publicData.includes('Covered by priced test items'));const changed=revise(w.project,{markup:30});assert.ok(approvalIssues({...w,project:changed}).length>0);w.project=draftVariation(w.project);w=recordApproval(w,'Synthetic client','Test evidence','VAR-001');assert.ok(financials(w.project).revenue>agreed)})
test('actuals consume commitments and remaining override is additional work; completion cannot hide commitments',()=>{const w=fixture();w.project.costs[0]={trade:'Preliminaries',actual:60,committed:100,remaining:20};let row=financials(w.project).rows[0];assert.equal(row.forecast,120);w.project.costs[0].actual=80;assert.equal(financials(w.project).rows[0].forecast,120);w.project.costs[0].complete=true;assert.equal(financials(w.project).rows[0].forecast,100);w.project.costs[0].actual=110;assert.equal(financials(w.project).rows[0].forecast,110);assert.ok(parseWorkspace(w));w.project.costs[0].remaining=-1;assert.equal(parseWorkspace(w),null)})
