import test from 'node:test'
import assert from 'node:assert/strict'
import {parseDocumentReading,validDocumentReadings,applyDocumentItems} from './studio-document-reading.ts'
import {newWorkspace,parseWorkspace,clientProjection} from './studio-workspace.ts'
import {totals} from './project-studio.ts'
const source={id:'a'.repeat(64),name:'Kitchen.pdf',pages:[{page:1,text:'Sink mixer quantity 2 supply $110 each GST included'}]}
const item={scope:'fixtures',name:'Sink mixer supply',unit:'each',quantity:2,basis:'Printed quantity 2. Installation excluded.',evidence:[{page:1,quote:'Sink mixer quantity 2'}],price:110,tax:'included',priceBasis:'Printed unit supply allowance'}
const raw=()=>({revision:'Draft',summary:'PRIVATE source details',items:[structuredClone(item)],questions:['Confirm installation.'],warnings:[],sheets:[{page:1,role:'schedule',title:'Kitchen'}]})
test('unmatched source quotes cannot become measured estimate items',()=>{const r=raw();r.items[0].evidence[0].quote='invented length 9000';const d=parseDocumentReading(r,source);assert.equal(d.items.length,0);assert.match(d.warnings[0],/Not imported/);assert.ok(validDocumentReadings([d]))})
test('PDF evidence normalizes whitespace but rejects wrong page references',()=>{const r=raw();r.items[0].evidence[0].quote='Sink   mixer quantity 2';assert.equal(parseDocumentReading(r,source).items.length,1);r.items[0].evidence[0].page=2;assert.equal(parseDocumentReading(r,source).items.length,0)})
test('draft takeoff imports without affecting accepted baseline and is idempotent',()=>{const w=newWorkspace();const d=parseDocumentReading(raw(),source);w.documentReadings=[d];w.project.baseline=structuredClone(w.project.working);const prior=JSON.stringify(w),next=applyDocumentItems(w,d.id,[d.items[0].id]);assert.equal(JSON.stringify(w),prior);assert.deepEqual(next.project.baseline,w.project.baseline);assert.equal(next.project.working.lines[0].rate,100);assert.equal(totals(next.project.working).cost,200);assert.equal(next.project.working.lines[0].rateVerified,false);assert.equal(next.scopeReview?.items.find(i=>i.key==='fixtures')?.status,'unknown');assert.ok(parseWorkspace(next));assert.throws(()=>applyDocumentItems(next,d.id,[d.items[0].id]),/twice/);assert.ok(!JSON.stringify(clientProjection(next)).includes('PRIVATE'))})
test('unknown quantities and tax treatment stay unmeasured and unpriced',()=>{const r:any=raw();r.items[0].quantity=null;r.items[0].tax='unknown';const d=parseDocumentReading(r,source),w=newWorkspace();w.documentReadings=[d];const next=applyDocumentItems(w,d.id,[d.items[0].id]);assert.equal(next.project.working.lines[0].quantity,0);assert.equal(next.project.working.lines[0].rate,0);assert.ok(next.project.working.lines[0].note.includes('110'))})
test('malformed persisted results cannot bypass validation',()=>{const w=newWorkspace();w.documentReadings=[parseDocumentReading(raw(),source)];w.documentReadings[0].items[0].price=Infinity;assert.equal(parseWorkspace(w),null);const r:any=raw();r.items[0].quantity=-2;assert.throws(()=>parseDocumentReading(r,source),/invalid quantities/);r.items[0].quantity=1;r.items[0].scope='unknown trade';assert.throws(()=>parseDocumentReading(r,source))})
