export const planningBase='https://mapprod3.environment.nsw.gov.au/arcgis/rest/services/Planning/EPI_Primary_Planning_Layers/MapServer'
export const terrainBase='https://portal.spatial.nsw.gov.au/server/rest/services/NSW_Elevation_and_Depth_Theme_multiCRS/MapServer/2'
export type SiteLayer={name:string;source:string;status:'found'|'no-match'|'unavailable';features:Record<string,string|number|null>[];note:string}
export type SiteReport={latitude:number;longitude:number;retrievedAt:string;layers:SiteLayer[];contours:{elevation:number;paths:number[][][]}[];terrainStatus:'found'|'no-match'|'unavailable';terrainNote:string;terrainSource:string}
const fields=['EPI_NAME','LGA_NAME','CURRENCY_DATE','COMMENCED_DATE','LAY_CLASS','SYM_CODE','PURPOSE','FSR','MAX_B_H','MAX_B_H_M','MAX_B_H_RL','UNITS','H_NAME','SIG','LEGIS_REF_CLAUSE','LEGIS_REF_VALUE','MAP_NAME']
export function siteLocation(v:any){if(!Number.isFinite(v?.latitude)||v.latitude< -37.6||v.latitude> -28||!Number.isFinite(v.longitude)||v.longitude<140.9||v.longitude>154)throw new Error('Enter coordinates within mainland NSW. Other jurisdictions are not connected yet.');return {latitude:v.latitude as number,longitude:v.longitude as number}}
export async function querySite(location:ReturnType<typeof siteLocation>,transport:typeof fetch=fetch):Promise<SiteReport>{
 const {latitude,longitude}=location
 async function request(url:string,params:Record<string,string>){const r=await transport(url+'/query?'+new URLSearchParams({f:'json',...params}),{signal:AbortSignal.timeout(18000)});if(!r.ok)throw new Error('Spatial service unavailable');const d=await r.json();if(d.error||!Array.isArray(d.features)||d.exceededTransferLimit)throw new Error('Spatial response incomplete');return d}
 const results=await Promise.allSettled(([['Heritage',0],['Floor space ratio',1],['Land zoning',2],['Building height',5]] as const).map(async([name,id])=>{
  const source=planningBase+'/'+id,d=await request(source,{geometry:longitude+','+latitude,geometryType:'esriGeometryPoint',inSR:'4326',spatialRel:'esriSpatialRelIntersects',outFields:'*',returnGeometry:'false',resultRecordCount:'20'})
  const features=d.features.map((f:any)=>Object.fromEntries(fields.filter(k=>f.attributes?.[k]!==undefined).map(k=>[k,typeof f.attributes[k]==='string'?f.attributes[k].slice(0,2000):typeof f.attributes[k]==='number'&&Number.isFinite(f.attributes[k])?f.attributes[k]:null])))
  return {name,source,features,status:features.length?'found':'no-match',note:'Point query only. Confirm the whole lot, current instrument and applicable exceptions.'} as SiteLayer
 }))
 const names=['Heritage','Floor space ratio','Land zoning','Building height'],ids=[0,1,2,5]
 const layers:SiteLayer[]=results.map((r,i)=>r.status==='fulfilled'?r.value:{name:names[i],source:planningBase+'/'+ids[i],status:'unavailable',features:[],note:'The source could not be read completely. This check remains unresolved.'})
 let contours:SiteReport['contours']=[],terrainStatus:SiteReport['terrainStatus']='unavailable',terrainNote='Terrain source unavailable. No elevation surface has been assumed.'
 try{const dy=200/111320,dx=dy/Math.cos(latitude*Math.PI/180),d=await request(terrainBase,{geometry:[longitude-dx,latitude-dy,longitude+dx,latitude+dy].join(','),geometryType:'esriGeometryEnvelope',inSR:'4326',outSR:'4326',spatialRel:'esriSpatialRelIntersects',outFields:'elevation,verticalaccuracy,featurereliabilitydate',returnGeometry:'true',geometryPrecision:'7',maxAllowableOffset:'0.00001',resultRecordCount:'200'})
  let points=0
  contours=d.features.map((f:any)=>{if(typeof f.attributes?.elevation!=='number'||!Number.isFinite(f.attributes.elevation)||!Array.isArray(f.geometry?.paths))throw new Error('Invalid contour');const paths=f.geometry.paths.map((p:any)=>{if(!Array.isArray(p))throw new Error('Invalid path');return p.map((a:any)=>{points++;if(points>40000||!Array.isArray(a)||!Number.isFinite(a[0])||!Number.isFinite(a[1]))throw new Error('Invalid point');return [a[0],a[1]]})});return {elevation:f.attributes.elevation,paths}})
  terrainStatus=contours.length?'found':'no-match';terrainNote='Regional contours intersecting a 400 m search window. Lines may extend beyond it. Not a site survey or an engineered ground surface.'
 }catch{}
 return {...location,retrievedAt:new Date().toISOString(),layers,contours,terrainStatus,terrainNote,terrainSource:terrainBase}
}
export function validSiteReport(v:any):v is SiteReport {
 try{siteLocation(v);return Number.isFinite(Date.parse(v.retrievedAt))&&Array.isArray(v.layers)&&v.layers.length===4&&v.layers.every((l:any)=>typeof l.name==='string'&&l.name.length<100&&l.source.startsWith(planningBase+'/')&&['found','no-match','unavailable'].includes(l.status)&&typeof l.note==='string'&&l.note.length<2000&&Array.isArray(l.features)&&l.features.length<=20&&l.features.every((f:any)=>Object.entries(f).every(([k,a])=>fields.includes(k)&&(a===null||typeof a==='string'&&a.length<=2000||typeof a==='number'&&Number.isFinite(a)))))&&['found','no-match','unavailable'].includes(v.terrainStatus)&&v.terrainSource===terrainBase&&typeof v.terrainNote==='string'&&v.terrainNote.length<2000&&Array.isArray(v.contours)&&v.contours.length<=200&&JSON.stringify(v.contours).length<2000000&&v.contours.every((c:any)=>Number.isFinite(c.elevation)&&Array.isArray(c.paths)&&c.paths.every((p:any)=>Array.isArray(p)&&p.every((a:any)=>Array.isArray(a)&&a.length===2&&Number.isFinite(a[0])&&Number.isFinite(a[1]))))}catch{return false}
}
export function screeningChecks(report:SiteReport,measuredHeight:number,assessedGFA:number,siteArea:number){
 const compare=(name:string,field:string,actual:number)=>{const layer=report.layers.find(l=>l.name===name),values=layer?.features.map(f=>f[field]);if(layer?.status!=='found'||!values?.length||values.some(v=>typeof v!=='number'||!Number.isFinite(v))||new Set(values).size!==1||!Number.isFinite(actual)||actual<=0)return {name,result:'Unresolved — confirm the applicable numeric control and proposal measurement.'};const limit=values[0] as number;return {name,result:`Entered value ${actual.toFixed(2)} / mapped value ${limit}: ${actual>limit?'exceeds mapped value':'within mapped value'}. Preliminary numeric comparison only; applicability and exceptions need review.`}}
 return [compare('Building height','MAX_B_H_M',measuredHeight),compare('Floor space ratio','FSR',siteArea>0?assessedGFA/siteArea:NaN),{name:'Approval pathway',result:'Unresolved. Zoning alone does not establish permissibility or DA/CDC eligibility. Review the current LEP, SEPP, DCP, lot-wide constraints and survey with a qualified reviewer.'}]
}
