import {test} from 'node:test'
import assert from 'node:assert/strict'
import {learnRate,lessonRate,tradeOutcomes} from './studio-learning.ts'
import {newWorkspace,parseWorkspace,clientProjection} from './studio-workspace.ts'
import {createDemoProject} from './project-studio.ts'
function fixture(){const p=createDemoProject();p.baseline=structuredClone(p.working);p.costs=p.costs.map(c=>({...c,actual:10000,committed:10000,complete:true}));p.baseline.lines[0].waste=10;return p}
test('observed rates remove waste from material and never modify agreed scope',()=>{const p=fixture(),before=JSON.stringify(p),l=learnRate(p,'site',{quantity:10,material:1100,labour:500,reason:'Invoice 1, same specification'},'lesson');assert.equal(l.rate,100);assert.equal(l.labourRate,50);const rate=lessonRate(l,p.baseline!.lines[0],'rate');assert.equal(rate.rateVerified,false);assert.equal(rate.wallId,undefined);assert.equal(JSON.stringify(p),before)})
test('unsettled, incomplete, impossible and unreferenced observations are rejected',()=>{const p=fixture(),input={quantity:10,material:1100,labour:500,reason:'Invoice 1'};p.costs[0].complete=false;assert.throws(()=>learnRate(p,'site',input,'a'),/Complete/);p.costs[0].complete=true;p.costs[0].committed=12000;assert.equal(tradeOutcomes(p)[0].ready,false);assert.throws(()=>learnRate(p,'site',input,'a'),/Complete/);p.costs[0].committed=0;assert.throws(()=>learnRate(p,'site',{...input,quantity:0},'a'));assert.throws(()=>learnRate(p,'site',{...input,material:20000},'a'),/exceed/);assert.throws(()=>learnRate(p,'site',{...input,reason:''},'a'),/reference/)})
test('lessons persist in backups and remain absent from client payloads',()=>{const w=newWorkspace(true);w.project=fixture();w.lessons=[learnRate(w.project,'site',{quantity:10,material:1100,labour:500,reason:'PRIVATE invoice'},'a')];assert.ok(parseWorkspace(w));assert.ok(!JSON.stringify(clientProjection(w)).includes('PRIVATE invoice'));w.lessons[0].rate=Infinity;assert.equal(parseWorkspace(w),null)})
