import test from 'node:test'
import assert from 'node:assert/strict'
import {createRenderRepository,renderPrefix,validSavedRender} from './studio-render-record.ts'
const alice='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',bob='bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',png='data:image/png;base64,iVBORw0KGgo='
function fixture(){const files=new Map<string,string>(),ownership=new Map([['project-a',alice],['project-b',bob]]);let reads=0,writes=0;const repo=createRenderRepository({async list(prefix){reads++;return Array.from(files.keys()).filter(k=>k.startsWith(prefix+'/')).map(k=>k.slice(prefix.length+1))},async read(key){reads++;if(!files.has(key))throw new Error('Not found');return files.get(key)!},async write(key,data){writes++;if(files.has(key))throw new Error('Already exists');files.set(key,data)}},async(owner,id)=>{if(ownership.get(id)!==owner)throw new Error('Project not found')});return {repo,files,counts:()=>({reads,writes})}}
const record={projectId:'project-a',revision:'{"width":8}',image:png,source:png,style:'Test only'}
test('saved render reopens with original model revision and source, independently of current design',async()=>{const {repo}=fixture(),saved=await repo.save(alice,record);assert.deepEqual(await repo.read(alice,'project-a',saved.id),saved);assert.deepEqual((await repo.list(alice,'project-a')).map(r=>r.id),[saved.id]);assert.equal(saved.revision,record.revision)})
test('cross-account list, read and save are rejected before object storage is touched',async()=>{const {repo,counts}=fixture(),saved=await repo.save(alice,record),before=counts();await assert.rejects(()=>repo.list(bob,'project-a'));await assert.rejects(()=>repo.read(bob,'project-a',saved.id));await assert.rejects(()=>repo.save(bob,record));assert.deepEqual(counts(),before);assert.deepEqual(await repo.list(bob,'project-b'),[])})
test('paths cannot escape owner and project; arbitrary URLs and oversized output cannot be saved',async()=>{const {repo,counts}=fixture();for(const id of ['../secret','x/y','x\\y','', 'a'.repeat(101)])assert.throws(()=>renderPrefix(alice,id));await assert.rejects(()=>repo.read(alice,'project-a','../../secret'));await assert.rejects(()=>repo.save(alice,{...record,image:'https://example.com/image.png'}));await assert.rejects(()=>repo.save(alice,{...record,image:png+'A'.repeat(24000100)}));assert.equal(counts().writes,0)})
test('quota prevents further writes; storage failures never report success',async()=>{const {repo,files}=fixture();for(let i=0;i<20;i++)files.set(alice+'/project-a/'+i+'.json','test');await assert.rejects(()=>repo.save(alice,record),/20 saved/);const broken=createRenderRepository({async list(){return []},async read(){throw new Error('Offline')},async write(){throw new Error('Offline')}},async()=>{});await assert.rejects(()=>broken.save(alice,record),/Offline/)})
test('corrupt or mislinked saved images are rejected on reopen',async()=>{const {repo,files}=fixture(),saved=await repo.save(alice,record);files.set(alice+'/project-a/'+saved.id+'.json',JSON.stringify({...saved,projectId:'project-b'}));await assert.rejects(()=>repo.read(alice,'project-a',saved.id),/invalid/);assert.equal(validSavedRender({...saved,projectId:undefined}),false)})
