import {test} from 'node:test'
import assert from 'node:assert/strict'
import {preparePriceDraft,markupForTotal} from './studio-price-draft.ts'
import {createDemoProject,totals,quotePackages} from './project-studio.ts'
import type {Line} from './project-studio.ts'
const line:Line={id:'w',trade:'Structure',name:'Garage west · Framing',unit:'m²',source:'wall-area',quantity:0,rate:0,included:true,allowance:false,note:'',rateVerified:false}
test('suggestions fill eligible missing rates, preserve existing prices and keep other scope unresolved',()=>{const r=createDemoProject().working;r.lines=[line,{...line,id:'priced',rate:80},{...line,id:'unsupported',name:'Garage west · Structural steel'},{...line,id:'excluded',included:false}];const d=preparePriceDraft(r,[]);assert.equal(d.suggested,1);assert.equal(d.missing,1);assert.equal(d.revision.lines[0].rate,55);assert.equal(d.revision.lines[0].labour,45);assert.equal(d.revision.lines[0].rateVerified,false);assert.equal(d.revision.lines[1].rate,80);assert.equal(d.revision.lines[3].rate,0);assert.equal(r.lines[0].rate,0)})
test('saved rate requires compatible coverage, unit and review',()=>{const r=createDemoProject().working;r.lines=[line];assert.equal(preparePriceDraft(r,[{...line,rate:70,rateVerified:true}]).saved,1);assert.equal(preparePriceDraft(r,[{...line,rate:70,unit:'lm',rateVerified:true}]).saved,0);assert.equal(preparePriceDraft(r,[{...line,rate:70,rateVerified:false}]).saved,0)})
test('selling adjustment preserves costs, exact cents and allocated quote totals across save roundtrip',()=>{const r=createDemoProject().working;const cost=totals(r).cost,target=totals(r).total*1.12;const adjusted={...r,markup:markupForTotal(r,target)};const saved=JSON.parse(JSON.stringify(adjusted));assert.equal(totals(saved).cost,cost);assert.ok(Math.abs(totals(saved).total-target)<0.02);assert.ok(Math.abs(quotePackages(saved).reduce((s,p)=>s+p.price,0)-totals(saved).price)<0.02);assert.throws(()=>markupForTotal(r,0));assert.throws(()=>markupForTotal(r,NaN));assert.throws(()=>markupForTotal(r,cost*3))})
