'use client'
import type {Workspace} from '@/lib/studio-workspace'
import {estimateReadiness} from '@/lib/studio-readiness'
import {scopeIssues} from '@/lib/studio-scope'
export default function BuilderJourney({workspace:w,step,onStep,onScope,onPrices,issues}:{workspace:Workspace;step:number;onStep:(step:number)=>void;onScope:()=>void;onPrices:()=>void;issues:string[]}){
 const ready=estimateReadiness(w.project.working),labels=['Check plans','Check quantities','Enter prices','Review quote']
 const hasModel=!!w.project.working.design.geometry,needsScope=!w.scopeReview||!!scopeIssues(w.scopeReview,w.project.working).length
 const next=!hasModel?{title:w.plan?'Generate your 3D house':'Add the floor plan',note:w.plan?'Your drawing is loaded. Generate the model and review any issues reported.':'Use a floor-plan page to start your 3D house.',action:()=>onStep(1)}:!ready.modelReviewed?{title:'Check your 3D house',note:'Check the dimensions and openings against your plans.',action:()=>onStep(2)}:needsScope?{title:'Confirm what’s included',note:'Check the drawing versions and work covered by this estimate.',action:onScope}:issues.length?{title:'Complete the missing costs',note:'Review the quantities and prices before sending an estimate.',action:onPrices}:{title:'Review your client estimate',note:'Check the final scope and allowances before sharing.',action:()=>onStep(4)}
 return <section className="wb-journey" aria-label="Your next step"><nav aria-label="Project steps">{labels.map((label,i)=><button key={label} aria-current={step===i+1?'step':undefined} onClick={()=>onStep(i+1)}><span>{i+1}</span>{label}</button>)}</nav><div className="wb-journey-intro"><div><p className="wb-eyebrow">{w.demo?'SAMPLE PROJECT':'NEXT STEP'}</p><h2>{next.title}</h2><p>{next.note}</p></div><button className="wb-primary" onClick={next.action}>{next.title} →</button></div><div className="wb-readiness" aria-label="Pricing progress"><span>{ready.included} items included</span>{ready.unpriced>0&&<button onClick={onPrices}>{ready.unpriced} items still need a price →</button>}{ready.uncheckedQuantities>0&&<button onClick={onPrices}>{ready.uncheckedQuantities} quantities to check →</button>}{ready.uncheckedRates>0&&<button onClick={onPrices}>{ready.uncheckedRates} prices to check →</button>}</div><details className="wb-check-details"><summary>{issues.length?'What still needs checking?':'Ready for your final review'}</summary>{issues.length?<ul>{issues.map(s=><li key={s}>{s}</li>)}</ul>:<p>Recorded checks are complete. Confirm the whole job is covered before quoting.</p>}<p>{ready.allowances} allowances · {ready.included} items in the draft estimate.</p></details></section>
}
