'use client'
import {useEffect,useState} from 'react'
import type {Workspace} from '@/lib/studio-workspace'
import {uid} from '@/lib/studio-workspace'
import {buildingDimensions,geometryBounds,levels,length,measurementError,polygonArea,replaceLevel,resizeLevel,unresolvedChecks} from '@/lib/studio-geometry'
import type {Geometry,FloorGeometry,Room} from '@/lib/studio-geometry'
import {cloneFloor,validBuilding,isolateFloorIds} from '@/lib/studio-building'
import {money,quantity,revise,totals} from '@/lib/project-studio'
import PlanEditor,{Numeric} from './PlanEditor'
import PlanModel from './PlanModel'
import DrawingSetReader from './DrawingSetReader'
import SiteIntelligence from './SiteIntelligence'

export default function BuildingStudio({workspace:w,onChange,onCheckpoint,selected,onSelect}:{workspace:Workspace;onChange:(w:Workspace)=>void;onCheckpoint?:(w:Workspace)=>Promise<void>;selected:string;onSelect:(id:string)=>void}){
  const g=w.project.working.design.geometry
  const [level,setLevel]=useState('ground'),[draft,setDraft]=useState<Geometry|null>(null),[undo,setUndo]=useState<Geometry|null>(null),[message,setMessage]=useState('')
  const [roomName,setRoomName]=useState('Living room'),[rx,setRx]=useState(0),[ry,setRy]=useState(0),[rw,setRw]=useState(3),[rd,setRd]=useState(3),[wallId,setWallId]=useState(''),[expected,setExpected]=useState(3),[source,setSource]=useState('')
  const model=draft||g,floors=model?levels(model):[],floor=floors.find(l=>l.id===level)||floors[0],f=floor?.geometry,b=f?geometryBounds(f):null
  useEffect(()=>{setDraft(null);setUndo(null)},[w.project.id])
  useEffect(()=>{setDraft(null)},[g])
  useEffect(()=>{if(g&&selected){const hit=levels(g).find(l=>l.geometry.walls.some(w=>w.id===selected));if(hit)setLevel(hit.id)}},[g,selected])
  function propose(next:Geometry){if(!validBuilding(next)){setMessage('That change creates invalid geometry. Check room boundaries, wall openings and dimensions.');return}setDraft(next);setMessage('Review the model and estimate changes below, then apply.')}
  function editFloor(next:FloorGeometry){if(model&&floor)propose(replaceLevel(model,floor.id,{...next,verified:false}))}
  function apply(next:Geometry){if(!validBuilding(next))return;setUndo(g||null);const beforeRooms=levels(g||next).flatMap(l=>l.geometry.rooms||[]),afterRooms=levels(next).flatMap(l=>l.geometry.rooms||[]);const changedFinishes=new Set(beforeRooms.filter(r=>afterRooms.find(a=>a.id===r.id)?.finish!==r.finish).map(r=>r.id));const lines=w.project.working.lines.map(l=>l.source==='room-area'&&(l.roomId?changedFinishes.has(l.roomId):changedFinishes.size>0)?{...l,rateVerified:false}:l);onChange({...w,project:revise(w.project,{design:buildingDimensions(next),lines})});setDraft(null);setMessage('Design applied. Review measurements and reconnect any removed cost links before accepting.')}
  const proxy:Workspace=g&&floor?{...w,project:{...w.project,working:{...w.project.working,design:buildingDimensions(levels(g).find(l=>l.id===floor.id)?.geometry||g)}}}:w
  function fromEditor(next:Workspace){const updated=next.project.working.design.geometry;if(g&&floor&&updated){const nextG=replaceLevel(g,floor.id,isolateFloorIds(g,floor.id,updated));if(!validBuilding(nextG)){setMessage('This edit moves a room or opening outside valid geometry. Adjust or remove it before moving the wall.');return}setUndo(null);onChange({...next,project:{...next.project,working:{...next.project.working,design:buildingDimensions(nextG)}}})}else onChange(next)}
  const before=totals(w.project.working),after=draft?totals({...w.project.working,design:buildingDimensions(draft)}):before
  return <>
    {g&&levels(g).length>1&&<label className="wb-floor-choice">Drawing edits apply to<select aria-label="Drawing destination floor" value={floor?.id||'ground'} disabled={!!draft} onChange={e=>{setLevel(e.target.value);onSelect('')}}>{levels(g).map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label>}
    {!draft&&<><p className="wb-hint">Drawing edits and generated geometry target {floor?.name||'Ground floor'}. Other floors are retained. Select the appropriate floor before tracing or generating.</p><PlanEditor key={floor?.id||'ground'} workspace={proxy} onChange={fromEditor} onCheckpoint={onCheckpoint?async next=>{const geometry=next.project.working.design.geometry;const combined=g&&floor&&geometry?replaceLevel(g,floor.id,isolateFloorIds(g,floor.id,geometry)):geometry;const updated={...next,project:{...next.project,working:{...next.project.working,design:combined?buildingDimensions(combined):next.project.working.design}}};if(combined&&!validBuilding(combined))throw new Error('Check model geometry before saving.');onChange(updated);await onCheckpoint(updated)}:undefined} selected={selected} onSelect={onSelect}/></>}
    <details className="wb-advanced"><summary>More drawing pages & whole-building generation</summary>
    <section className="wb-card"><div className="wb-card-title"><div><h2>Drawing set</h2><p>Keep up to eight selected drawing pages with this project. New PDF uploads retain the original privately; use Review all pages to change the reading selection.</p></div></div><div className="wb-drawing-grid">{(w.drawings||[w.plan].filter(Boolean)).map((p,i)=>p&&<button key={i} aria-pressed={w.plan?.name===p.name&&w.plan.page===p.page} onClick={()=>{onChange({...w,plan:p});setMessage('Drawing selected. Set the destination floor below before generating or tracing.')}}><img src={p.image} alt={'Drawing '+p.name+' page '+p.page}/><strong>{p.name}</strong><span>Page {p.page} · {p.role||'Unclassified'}{p.revision?' · '+p.revision:''}</span></button>)}</div>{w.plan&&<button onClick={()=>onChange({...w,plan:null,drawings:w.drawings?.filter(p=>!(p.name===w.plan!.name&&p.page===w.plan!.page))})}>Remove selected page from library</button>}{w.plan&&<div className="wb-fields"><label>Drawing type<select value={w.plan.role||'other'} onChange={e=>onChange({...w,plan:{...w.plan!,role:e.target.value as any}})}>{['floor-plan','elevation','section','survey','other'].map(a=><option key={a}>{a}</option>)}</select></label><label>Drawing revision<input value={w.plan.revision||''} maxLength={100} onChange={e=>onChange({...w,plan:{...w.plan!,revision:e.target.value}})}/></label></div>}</section>
    <DrawingSetReader workspace={w} onChange={onChange} onCheckpoint={onCheckpoint}/>
    </details>
    <details className="wb-advanced"><summary>Site & planning research (optional)</summary><SiteIntelligence key={w.project.id} workspace={w} onChange={onChange}/></details>
    <details className="wb-advanced"><summary>Advanced model editing · floors, rooms, finishes & roofs</summary>
    {g&&floor&&f&&b&&<section className="wb-card"><div className="wb-card-title"><div><h2>Floors, rooms & finishes</h2><p>Model elements remain editable. New geometry needs measurement review.</p></div><select aria-label="Editing floor" value={floor.id} disabled={!!draft} onChange={e=>{setLevel(e.target.value);onSelect('');setWallId('')}}>{levels(g).map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></div>
      <div className="wb-toolbar"><button disabled={!!draft||(g.storeys?.length||0)>=4} onClick={()=>{const id=uid(),top=Math.max(...levels(g).map(l=>l.elevation+Math.max(...l.geometry.walls.map(w=>w.height),2.7)));propose({...g,storeys:[...(g.storeys||[]),{id,name:'Level '+((g.storeys?.length||0)+1),elevation:Math.round((top+.3)*100)/100,geometry:cloneFloor(f)}]})}}>Copy as new upper floor</button>{floor.id!=='ground'&&<button onClick={()=>propose({...model!,storeys:model!.storeys?.filter(l=>l.id!==floor.id)})}>Remove this floor</button>}<span>{floors.length} floor{floors.length===1?'':'s'} · {polygonArea(f.footprint).toFixed(2)} m² on this floor</span></div>
      {floor.id!=='ground'&&<div className="wb-fields"><label>Floor name<input maxLength={100} value={floor.name} onChange={e=>propose({...model!,storeys:model!.storeys?.map(l=>l.id===floor.id?{...l,name:e.target.value}:l)})}/></label><label>Elevation (m)<Numeric label="Floor elevation" value={floor.elevation} min={.2} max={30} onChange={n=>propose({...model!,storeys:model!.storeys?.map(l=>l.id===floor.id?{...l,elevation:n}:l)})}/></label></div>}
      <details><summary>Resize this floor</summary><p>Scales walls, rooms and opening widths together. Existing dimension checks will show discrepancies.</p><div className="wb-fields"><label>Width (m)<Numeric label="Design floor width" value={b.width} min={.5} max={100} onChange={n=>editFloor(resizeLevel(f,n/b.width,1))}/></label><label>Depth (m)<Numeric label="Design floor depth" value={b.depth} min={.5} max={100} onChange={n=>editFloor(resizeLevel(f,1,n/b.depth))}/></label></div></details>
      <details><summary>Rooms & floor finishes</summary><p>Define rectangular rooms using the drawing origin in metres. Furniture is illustrative and not included in quantities. Review material rates after changing a finish.</p><div className="wb-fields"><label>Room name<input value={roomName} maxLength={200} onChange={e=>setRoomName(e.target.value)}/></label>{([{label:'Room X',value:rx,set:setRx,min:-100},{label:'Room Y',value:ry,set:setRy,min:-100},{label:'Room width',value:rw,set:setRw,min:.2},{label:'Room depth',value:rd,set:setRd,min:.2}]).map(a=><label key={a.label}>{a.label}<Numeric label={a.label} value={a.value} min={a.min} max={100} onChange={a.set}/></label>)}<button disabled={(f.rooms?.length||0)>=80} onClick={()=>editFloor({...f,rooms:[...(f.rooms||[]),{id:uid(),name:roomName||'Room',polygon:[{x:rx,y:ry},{x:rx+rw,y:ry},{x:rx+rw,y:ry+rd},{x:rx,y:ry+rd}],finish:'oak',furniture:'none'}]})}>Add room</button></div>
      {(f.rooms||[]).map(r=><div className="wb-project-row" key={r.id}><span><strong>{r.name}</strong> · {polygonArea(r.polygon).toFixed(2)} m²</span><label>Floor finish<select value={r.finish} onChange={e=>editFloor({...f,rooms:f.rooms?.map(a=>a.id===r.id?{...a,finish:e.target.value as Room['finish']}:a)})}>{['oak','tile','concrete','carpet'].map(s=><option key={s}>{s}</option>)}</select></label><label>Furniture<select value={r.furniture} onChange={e=>editFloor({...f,rooms:f.rooms?.map(a=>a.id===r.id?{...a,furniture:e.target.value as Room['furniture']}:a)})}>{['none','living','bedroom','dining','kitchen-island','kitchen-wall','lift'].map(s=><option key={s}>{s}</option>)}</select></label><button onClick={()=>editFloor({...f,rooms:f.rooms?.filter(a=>a.id!==r.id)})}>Remove room</button><button disabled={!!draft||w.project.working.lines.some(l=>l.roomId===r.id)} onClick={()=>onChange({...w,project:revise(w.project,{lines:[...w.project.working.lines,{id:uid(),name:r.name+' floor finish',trade:'Interiors',unit:'m²',source:'room-area',roomId:r.id,rate:0,labour:0,quantity:0,included:true,allowance:false,rateVerified:false,note:'Enter the selected finish material and installation rate.'}]})})}>Link estimate item</button></div>)}</details>
      <details><summary>Wall colours</summary><div className="wb-fields">{f.walls.map(wall=><label key={wall.id}>{wall.name}<input aria-label={wall.name+' colour'} type="color" value={wall.colour||'#e4e4d8'} onChange={e=>editFloor({...f,walls:f.walls.map(a=>a.id===wall.id?{...a,colour:e.target.value}:a)})}/></label>)}</div></details>
      <details><summary>Concept roof</summary><p>Gable roof uses this floor’s rectangular bounds. Flat roofs use the footprint without overhang. Confirm the roof outline, pitch and overhang against drawings; this is not engineered geometry.</p><div className="wb-fields"><label>Roof form<select value={f.roof?.style||'none'} onChange={e=>editFloor({...f,roof:{pitch:25,axis:'x',overhang:.45,colour:'#535e60',...f.roof,style:e.target.value as any}})}>{['none','flat','gable'].map(s=><option key={s}>{s}</option>)}</select></label>{f.roof&&<><label>Pitch °<Numeric label="Roof pitch" value={f.roof.pitch} min={0} max={60} onChange={n=>editFloor({...f,roof:{...f.roof!,pitch:n}})}/></label><label>Overhang (m)<Numeric label="Roof overhang" value={f.roof.overhang} min={0} max={2} onChange={n=>editFloor({...f,roof:{...f.roof!,overhang:n}})}/></label><label>Ridge direction<select value={f.roof.axis} onChange={e=>editFloor({...f,roof:{...f.roof!,axis:e.target.value as 'x'|'y'}})}><option value="x">Across width</option><option value="y">Across depth</option></select></label><label>Roof colour<input type="color" value={f.roof.colour} onChange={e=>editFloor({...f,roof:{...f.roof!,colour:e.target.value}})}/></label></>}</div></details>
      <details><summary>Printed dimension checks</summary><p>Enter a dimension from the drawing. Differences over 50 mm require correction before acceptance.</p><div className="wb-fields"><label>Measured wall<select value={wallId} onChange={e=>setWallId(e.target.value)}><option value="">Choose wall</option>{f.walls.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Printed length (m)<Numeric label="Printed length" value={expected} min={.01} max={100} onChange={setExpected}/></label><label>Drawing reference<input value={source} maxLength={1000} onChange={e=>setSource(e.target.value)} placeholder="Sheet A101, dimension D1"/></label><button disabled={!wallId||!source.trim()} onClick={()=>{const wall=f.walls.find(a=>a.id===wallId);if(wall)editFloor({...f,checks:[...(f.checks||[]),{id:uid(),label:wall.name,a:wall.a,b:wall.b,expected,tolerance:.05,source}]})}}>Add dimension check</button></div>{f.checks?.map(m=><div key={m.id} className="wb-project-row"><span>{m.label}: model {length(m.a,m.b).toFixed(3)} m / drawing {m.expected.toFixed(3)} m · {Math.round(measurementError(m)*1000)} mm difference · {measurementError(m)>m.tolerance?'Needs correction':'Within tolerance'}<small>{m.source}</small></span><button onClick={()=>editFloor({...f,checks:f.checks?.filter(a=>a.id!==m.id)})}>Remove check</button></div>)}</details>
    </section>}
    </details>
    {message&&<p role="status" className="wb-notice">{message}</p>}
    {draft&&<section className="wb-card"><h2>Review design change</h2><PlanModel design={buildingDimensions(draft)} title="Proposed design change"/><p>Estimate change: <strong>{money(after.total-before.total)} incl GST</strong>. Missing or unreviewed rates remain unpriced or provisional.</p><div className="wb-table-scroll"><table><thead><tr><th>Item</th><th>Current quantity</th><th>Proposed quantity</th></tr></thead><tbody>{w.project.working.lines.filter(l=>quantity(l,w.project.working.design)!==quantity(l,buildingDimensions(draft))).map(l=><tr key={l.id}><td>{l.name}</td><td>{quantity(l,w.project.working.design)} {l.unit}</td><td>{quantity(l,buildingDimensions(draft))} {l.unit}</td></tr>)}</tbody></table></div><p>{unresolvedChecks(draft).length} dimension checks need correction.</p><button onClick={()=>apply(draft)}>Apply design change</button><button onClick={()=>{setDraft(null);setMessage('Proposed change discarded.')}}>Discard change</button></section>}
    {undo&&!draft&&<button onClick={()=>{const previous=undo;setUndo(null);onChange({...w,project:revise(w.project,{design:buildingDimensions(previous)})});setMessage('Previous geometry restored as a new revision.')}}>Undo last design change</button>}

  </>
}
