'use client'
import type {Workspace} from '@/lib/studio-workspace'
import {estimateReadiness} from '@/lib/studio-readiness'
import {scopeIssues} from '@/lib/studio-scope'
export default function BuilderJourney({workspace:w,step,onStep,onScope,onPrices,issues}:{workspace:Workspace;step:number;onStep:(step:number)=>void;onScope:()=>void;onPrices:()=>void;issues:string[]}){
 const ready=estimateReadiness(w.project.working),labels=['Plans','Optional 3D','Builder review','Client quote']
 const hasModel=!!w.project.working.design.geometry,needsScope=!w.scopeReview||!!scopeIssues(w.scopeReview,w.project.working).length
 const hasEvidence=!!(w.plan||w.drawings?.length||w.documentReadings?.length)
 const next=!hasEvidence&&!w.project.working.lines.length?{title:'Upload your plans',note:'WorkA will prepare a provisional scope and cost estimate for your review. A 3D model is optional.',action:()=>onStep(1)}:!w.builderReview?{title:'Prepare your builder estimate',note:'Start with proposed scope, quantities and average cost allowances. Review the assumptions afterwards.',action:onPrices}:{title:'Review your job costs',note:'Check the scope, quantities, provisional sums and optional work. Nothing is sent to a client.',action:onPrices}

 return <section className="wb-journey" aria-label="Your next step"><nav aria-label="Project steps">{labels.map((label,i)=><button key={label} aria-current={step===i+1?'step':undefined} onClick={()=>onStep(i+1)}><span>{i+1}</span>{label}</button>)}</nav><div className="wb-journey-intro"><div><p className="wb-eyebrow">{w.demo?'SAMPLE PROJECT':'NEXT STEP'}</p><h2>{next.title}</h2><p>{next.note}</p></div><button className="wb-primary" onClick={next.action}>{next.title} →</button></div><div className="wb-readiness" aria-label="Pricing progress"><span>{ready.included} items included</span>{ready.unpriced>0&&<button onClick={onPrices}>{ready.unpriced} items still need a price →</button>}{ready.uncheckedQuantities>0&&<button onClick={onPrices}>{ready.uncheckedQuantities} quantities to check →</button>}{ready.uncheckedRates>0&&<button onClick={onPrices}>{ready.uncheckedRates} prices to check →</button>}</div><details className="wb-check-details"><summary>{issues.length?'What still needs checking?':'Ready for your final review'}</summary>{issues.length?<ul>{issues.map(s=><li key={s}>{s}</li>)}</ul>:<p>Recorded checks are complete. Confirm the whole job is covered before quoting.</p>}<p>{ready.allowances} allowances · {ready.included} items in the draft estimate.</p></details></section>
}
