'use client'
import {useState} from 'react'
import type {Workspace} from '@/lib/studio-workspace'
import {createBudgetPlan,budgetPreview,applyBudget} from '@/lib/studio-budget'
import type {BudgetChoice} from '@/lib/studio-budget'
import {money,totals,sameRevision,lineCost} from '@/lib/project-studio'
import {allRooms} from '@/lib/studio-geometry'
import PlanModel from './PlanModel'

export default function DesignToBudget({workspace:w,onChange,onClose}:{workspace:Workspace;onChange:(w:Workspace)=>void;onClose:()=>void}){
 const [mode,setMode]=useState<'finishes'|'balanced'|'maximum'>('balanced'),[confirmed,setConfirmed]=useState(false),[message,setMessage]=useState(''),[showModel,setShowModel]=useState(false)
 const plan=w.budget||createBudgetPlan(w.project.working),base=totals(plan.base),preview=budgetPreview(plan,mode),stale=!sameRevision(plan.base,w.project.working)
 const put=(next:typeof plan)=>{setConfirmed(false);setMessage('');onChange({...w,budget:next})}
 const patch=(id:string,change:Partial<BudgetChoice>)=>put({...plan,choices:plan.choices.map(c=>c.id===id?{...c,...change}:c)})
 return <section className="wb-card wb-budget" aria-label="Design to budget"><div className="wb-card-title"><div><p className="wb-eyebrow">EXPLORE THE TRADE-OFFS</p><h2>Design to budget</h2></div><button onClick={onClose}>Close budget planner</button></div>
 <p>Set a client budget, protect their priorities and compare alternatives. Suggestions use provisional allowance reductions, not AI-verified prices. Nothing changes in the working estimate until you apply a proposal.</p>
 {stale&&<p role="alert">The estimate has changed. <button onClick={()=>put(createBudgetPlan(w.project.working))}>Refresh from current estimate</button> This resets your budget choices.</p>}
 <label>Client budget · including GST<input aria-label="Client budget including GST" type="number" min="0" max="1000000000" step="1000" value={plan.target} onChange={e=>{const n=Number(e.target.value);if(Number.isFinite(n)&&n>=0&&n<=1e9)put({...plan,target:n})}}/></label>
 <input aria-label="Budget slider" type="range" min="0" max={Math.max(base.total,plan.target,1)} step="1000" value={plan.target} onChange={e=>put({...plan,target:Number(e.target.value)})}/>
 <div className="wb-metrics"><div><span>Starting estimate · incl GST</span><strong>{money(base.total)}</strong></div><div><span>Client budget · incl GST</span><strong>{money(plan.target)}</strong></div><div><span>Savings needed</span><strong>{money(Math.max(0,base.total-plan.target))}</strong></div></div>
 <p className="wb-hint">Structure, essential services, compliance work, contingency and markup are protected. Already omitted items cannot produce another saving. Larger layout changes require a separately designed and costed option.</p>
 <h3>Client priorities and replacement allowances</h3><p>“Lower priority” means consider changing the selection first; it does not authorise removing essential parts of a bundled item. Enter the full replacement cost excluding GST, plus any associated work.</p>
 {!plan.choices.length&&<p>No suitable selection allowances found. Add separately priced interior selections to the estimate before using this planner. No automatic structural removals are available.</p>}
 {plan.choices.map(c=>{const line=plan.base.lines.find(l=>l.id===c.lineId);if(!line)return null;const rooms=plan.base.design.geometry?allRooms(plan.base.design.geometry).filter(r=>r.finish==='oak'&&!/bath|ensuite|kitchen|laundry|balcony|patio|alfresco/i.test(r.name)):[];return <details key={c.id} className="wb-budget-choice"><summary>{c.title} · {c.priority==='keep'?'Protected':money(Math.max(0,lineCost(line,plan.base.design)-c.replacement-c.extra))+' potential cost saving ex GST'} · {c.reviewed&&c.reference.trim()?'Builder reviewed':'Provisional'}</summary><p>{line.name} · current direct cost {money(lineCost(line,plan.base.design))}</p><div className="wb-fields"><label>Priority for {c.title}<select value={c.priority} onChange={e=>patch(c.id,{priority:e.target.value as BudgetChoice['priority']})}><option value="keep">Must keep unchanged</option><option value="flexible">Flexible selection</option><option value="remove">Lower priority — change first</option></select></label><label>Replacement cost ex GST<input type="number" min="1" max="1000000000" value={c.replacement} onChange={e=>patch(c.id,{replacement:Math.max(0,Math.min(1e9,Number(e.target.value)||0)),reviewed:false})}/></label><label>Associated work ex GST<input type="number" min="0" max="1000000000" value={c.extra} onChange={e=>patch(c.id,{extra:Math.max(0,Math.min(1e9,Number(e.target.value)||0)),reviewed:false})}/></label><label>Builder / supplier reference<input maxLength={1000} value={c.reference} onChange={e=>patch(c.id,{reference:e.target.value,reviewed:false})}/></label></div><label>Scope and dependencies<textarea maxLength={2000} value={c.note} onChange={e=>patch(c.id,{note:e.target.value,reviewed:false})}/></label><label><input type="checkbox" checked={c.reviewed} disabled={!c.reference.trim()} onChange={e=>patch(c.id,{reviewed:e.target.checked})}/>Builder reviewed replacement scope, associated costs and performance</label>{/floor finishes/i.test(line.name)&&rooms.length>0&&<fieldset><legend>Illustrate carpet instead of timber in selected dry rooms</legend><p>Choose only rooms covered by this replacement allowance. Room sizes and stairs stay unchanged.</p>{rooms.map(room=><label key={room.id}><input type="checkbox" checked={c.floorRooms.includes(room.id)} onChange={e=>patch(c.id,{floorRooms:e.target.checked?[...c.floorRooms,room.id]:c.floorRooms.filter(id=>id!==room.id),reviewed:false})}/>{room.name}</label>)}</fieldset>}{c.replacement<=0&&<p role="alert">Enter a positive replacement cost. Whole-item omissions are not supported here.</p>}</details>})}
 <h3>Compare budget packages</h3><div className="wb-budget-packages">{([{id:'finishes',name:'Flexible selections',note:'Keep lower-priority items as they are.'},{id:'balanced',name:'Priorities first',note:'Consider lower-priority selections first; stop when the target is met.'},{id:'maximum',name:'All available alternatives',note:'Show every allowed saving, even when the target remains out of reach.'}] as const).map(p=>{const v=budgetPreview(plan,p.id);return <button key={p.id} aria-pressed={mode===p.id} onClick={()=>{setMode(p.id);setConfirmed(false)}}><strong>{p.name}</strong><span>{money(v.after.total)} incl GST</span><small>{p.note}</small></button>})}</div>
 <div className="wb-metrics"><div><span>Proposed total · incl GST</span><strong>{money(preview.after.total)}</strong></div><div><span>Client saving · incl GST</span><strong>{money(preview.saving)}</strong></div><div><span>Still above budget</span><strong>{money(preview.gap)}</strong></div></div>
 <p role="status">{preview.gap>0?'The available alternatives do not meet this budget. Further scope/design review is needed.':'The proposed total is within the target.'} {preview.provisional?'Selected savings are provisional and need builder confirmation.':'Review the underlying estimate as well as these alternatives.'}</p>
 <p>Proposed direct cost {money(preview.after.cost)} ex GST · gross profit {money(preview.after.profit)} (change {money(preview.after.profit-base.profit)}) · margin {preview.after.margin.toFixed(1)}%. Markup stays at {plan.base.markup}%. No cash-flow receipts or payment dates are created.</p>
 <ul>{preview.selected.map(c=><li key={c.id}>{c.title} — {c.note}</li>)}</ul>
 <button onClick={()=>setShowModel(!showModel)}>{showModel?'Hide model comparison':'Show before & proposed 3D'}</button>{showModel&&<><p>Only explicitly selected room finishes change visually. Joinery/appliance allowance changes have no detailed model representation. Walls, rooms and structure remain intact.</p><div className="wb-comparison"><div><h3>Before</h3><PlanModel design={plan.base.design} title="Before budget changes" compactControls/></div><div><h3>Proposed</h3><PlanModel design={preview.revision.design} title="Budget proposal" compactControls/></div></div></>}
 <p><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I have reviewed the selected changes and understand any provisional pricing.</label></p><button disabled={stale||!confirmed||!preview.selected.length||w.options.length>10} onClick={()=>{try{onChange(applyBudget(w,plan,mode));setConfirmed(false);setMessage('Proposal applied to working scope. Before and after options are retained. Save project to keep a checkpoint; contract approval is separate.')}catch(e){setMessage((e as Error).message)}}}>Apply proposal to working scope</button>{w.options.length>10&&<p>Two free saved-option slots are required to retain the before and after designs.</p>}{message&&<p role="status">{message}</p>}
 </section>
}
