'use client'
import {useEffect,useRef,useState} from 'react'
import {drawingFingerprint} from '@/lib/studio-model-progress'
import {generateBuildingDraft} from '@/lib/studio-generate-building'
import {prepareLinkedTakeoff} from '@/lib/studio-draft-takeoff'
import type {Workspace} from '@/lib/studio-workspace'
import type {recognisedSet} from '@/lib/studio-set-recognition'
import {revise,totals,money,quantity} from '@/lib/project-studio'
import PlanModel from './PlanModel'
export default function DrawingSetReader({workspace:w,onChange,onCheckpoint}:{workspace:Workspace;onChange:(w:Workspace)=>void;onCheckpoint?:(w:Workspace)=>Promise<void>}){
 const [available,setAvailable]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[draft,setDraft]=useState<ReturnType<typeof recognisedSet>|null>(null)
 const latest=useRef(w);latest.current=w
 const pages=w.drawings?.length?w.drawings:w.plan?[w.plan]:[],stamp=JSON.stringify([w.project.id,w.project.working,pages]),current=useRef(stamp),controller=useRef<AbortController|null>(null),generation=useRef(0),draftStamp=useRef('');current.current=stamp
 useEffect(()=>{const c=new AbortController();void fetch('/api/studio/recognise',{signal:c.signal}).then(r=>r.json()).then(d=>setAvailable(d.available===true)).catch(()=>{});return()=>{c.abort();controller.current?.abort();generation.current++}},[])
 useEffect(()=>{generation.current++;controller.current?.abort();setBusy(false);setDraft(null)},[stamp])
 async function generate(){const id=++generation.current,c=new AbortController();controller.current=c;setBusy(true);setDraft(null);setMessage('Reading the selected drawing set together…');const timer=setTimeout(()=>c.abort(),660000);try{const source=await drawingFingerprint(pages);const v=await generateBuildingDraft(pages,c.signal,setMessage,fetch,{previousDraft:w.modelProgress?.source===source?w.modelProgress.draft:undefined,save:async(draft,error)=>{if(id!==generation.current||current.current!==stamp)throw new Error('Project changed.');const updated={...latest.current,modelProgress:{source,draft,error,at:new Date().toISOString()}};onChange(updated);if(onCheckpoint)await onCheckpoint(updated)}});if(id===generation.current&&current.current===stamp){draftStamp.current=stamp;setDraft(v);setMessage('Review every floor, level, alignment and assumption before applying.')}}catch(e){if(id===generation.current)setMessage(c.signal.aborted?'Reading stopped. The provider may still complete this request; the model is unchanged.':e instanceof Error?e.message:'Reading failed.')}finally{clearTimeout(timer);if(id===generation.current)setBusy(false)}}
 return <section className="wb-card"><h3>Drawing set → building draft</h3><p>Read up to eight saved pages together. Include floor plans, elevations and sections from the same revision. The API proposes separate floors and reports missing evidence.</p><p>{pages.length} page(s) will be sent to the configured AI provider. Remove superseded sheets before generating.</p>{!available&&<p>Connect an AI API on the server to enable drawing-set reading.</p>}<button disabled={!available||busy||!pages.length} onClick={()=>void generate()}>{busy?'Reading drawing set…':w.modelProgress?'Resume building draft':'Generate building from drawing set'}</button>{busy&&<button onClick={()=>controller.current?.abort()}>Stop reading</button>}{message&&<p role="status">{message}</p>}{w.setReview&&!draft&&<details><summary>Last drawing-set assumptions</summary><p>{w.setReview.at}</p><ul>{w.setReview.warnings.map((s,i)=><li key={i}>{s}</li>)}</ul></details>}{draft&&<><PlanModel design={draft.design} title="Drawing-set draft — review required"/><p>Proposed estimate difference: {money(totals({...w.project.working,design:draft.design}).total-totals(w.project.working).total)} incl GST. Regenerated element IDs require reconnecting estimate links.</p><ul>{w.project.working.lines.filter(l=>quantity(l,w.project.working.design)!==quantity(l,draft.design)).map(l=><li key={l.id}>{l.name}: {quantity(l,w.project.working.design)} → {quantity(l,draft.design)} {l.unit}</li>)}</ul><ul>{draft.warnings.map((s,i)=><li key={i}>{s}</li>)}</ul><button onClick={async()=>{if(draftStamp.current!==current.current)return;const updated={...w,demo:false,modelProgress:undefined,setReview:{at:new Date().toISOString(),warnings:draft.warnings},project:revise(w.project,{design:draft.design})};let next:Workspace=updated;let note='';if(!w.project.working.design.geometry){try{const prepared=prepareLinkedTakeoff(updated,w.scopeReview?.kind==='new-build');next=prepared.workspace;note=` ${prepared.added} linked cost items prepared; review scope and rates.`}catch(e){note=' '+(e as Error).message}}onChange(next);setDraft(null);try{if(onCheckpoint)await onCheckpoint(next);setMessage('Draft applied and saved. Review all floors and quantities.'+note)}catch(e){setMessage('Draft applied, but saving needs attention: '+(e as Error).message)}}}>Apply building draft</button><button onClick={()=>setDraft(null)}>Discard building draft</button></>}</section>
}
