'use client'
import type {Workspace} from '@/lib/studio-workspace'
import {estimateReadiness} from '@/lib/studio-readiness'
export default function EstimateGuide({workspace:w,step,onStep,issues}:{workspace:Workspace;step:number;onStep:(step:number)=>void;issues:string[]}){
 const ready=estimateReadiness(w.project.working),labels=['Upload plans','Check the model','Review prices','Prepare estimate']
 const descriptions=['Start with a floor-plan PDF or image. You can also enter known dimensions.','Check the scale, walls and openings against the drawing. Review every floor before pricing.','Add the work you intend to include, enter your rates and check each item.','Review the client-facing scope, allowances and exclusions before sharing.']
 const next=step===1?2:step===2?3:step===3?4:3
 return <section className="wb-journey" aria-label="Estimate workflow"><nav aria-label="Estimate steps">{labels.map((label,i)=><button key={label} aria-current={step===i+1?'step':undefined} onClick={()=>onStep(i+1)}><span>{i+1}</span>{label}</button>)}</nav><div className="wb-journey-intro"><div><p className="wb-eyebrow">STEP {step} OF 4{w.demo?' · SAMPLE PROJECT':''}</p><h2>{labels[step-1]}</h2><p>{descriptions[step-1]}</p></div><button onClick={()=>onStep(next)}>{step===4?'Back to pricing':labels[next-1]+' →'}</button></div><div className="wb-readiness" aria-label="Estimate readiness"><span>{ready.modelReviewed?'✓ Measurements reviewed':'Measurements need review'}</span><span>{ready.included} included items</span>{ready.unpriced>0&&<button className="wb-attention" onClick={()=>onStep(3)}>{ready.unpriced} unpriced</button>}{ready.missingQuantities>0&&<button className="wb-attention" onClick={()=>onStep(3)}>{ready.missingQuantities} need quantities</button>}{ready.uncheckedQuantities>0&&<button onClick={()=>onStep(3)}>{ready.uncheckedQuantities} quantities to check</button>}{ready.uncheckedRates>0&&<button onClick={()=>onStep(3)}>{ready.uncheckedRates} rates to check</button>}<span>{issues.length?'Draft · review needed':'Checks complete · builder sign-off needed'}</span></div>{step===4&&<div className="wb-quote-checks"><h3>Before this becomes a client quote</h3>{issues.length?<ul>{issues.map(s=><li key={s}>{s}</li>)}</ul>:<p>The recorded measurement and pricing checks are complete. Confirm that the scope covers the entire job.</p>}<p>{ready.allowances} allowance(s). Confirm inclusions, exclusions, supplier quotes, access and site conditions with your builder. A completed checklist does not guarantee a complete estimate.</p></div>}</section>
}
