'use client'
import {useEffect,useRef,useState} from 'react'
export default function PhotorealisticRender({capture,title,revision}:{capture:()=>string|undefined;title:string;revision:string}){
 const [available,setAvailable]=useState(false),[busy,setBusy]=useState(false),[style,setStyle]=useState('Natural daylight, warm timber, soft neutral finishes, realistic architectural photography.'),[message,setMessage]=useState(''),[result,setResult]=useState<{image:string;source:string;revision:string}|null>(null)
 const controller=useRef<AbortController|null>(null),generation=useRef(0)
 useEffect(()=>{const c=new AbortController();void fetch('/api/studio/recognise',{signal:c.signal}).then(r=>r.json()).then(d=>setAvailable(d.images===true)).catch(()=>{});return()=>{c.abort();generation.current++;controller.current?.abort()}},[])
 async function generate(){const source=capture();if(!source){setMessage('Wait for the 3D model to load.');return}const id=++generation.current,c=new AbortController();controller.current=c;setBusy(true);setMessage('Generating a visualisation from this view. This can take a few minutes.');const timer=setTimeout(()=>c.abort(),225000);try{const r=await fetch('/api/studio/render',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image:source,style,title:title.slice(0,200)}),signal:c.signal}),v=await r.json();if(!r.ok)throw new Error(v.error);if(id===generation.current){setResult({image:v.image,source,revision});setMessage(v.label)}}catch(e){if(id===generation.current)setMessage(c.signal.aborted?'Stopped waiting. The provider may still finish and charge for this request.':e instanceof Error?e.message:'Image generation failed.')}finally{clearTimeout(timer);if(id===generation.current)setBusy(false)}}
 return <details className="wb-photo-render"><summary>Photorealistic visualisation</summary><p>Generate from the current camera view and visible floors. The snapshot and preferences are sent to OpenAI. The editable model and estimate remain the measurement source.</p><label>Materials & lighting<textarea maxLength={1500} value={style} onChange={e=>setStyle(e.target.value)}/></label>{!available&&<p>Connect the OpenAI image API on the Worka server to enable rendering.</p>}<button disabled={!available||busy} onClick={()=>void generate()}>{busy?'Generating image…':'Generate photorealistic image'}</button>{busy&&<button onClick={()=>controller.current?.abort()}>Stop waiting</button>}{message&&<p role="status">{message}</p>}{result&&<><p>{result.revision!==revision?'This image belongs to an earlier model revision. ':''}Illustrative AI output — review against the model.</p><div className="wb-render-compare"><figure><img src={result.source} alt="Source model snapshot"/><figcaption>Model snapshot sent to the API</figcaption></figure><figure><img src={result.image} alt="AI architectural visualisation"/><figcaption>AI concept visualisation · not for measurement</figcaption></figure></div><a href={result.image} download="worka-ai-concept.png">Download visualisation</a><p>Download to keep this image; it is not saved in project checkpoints.</p></>}</details>
}
