'use client'
import {matchesJson} from '@/lib/studio-json'
import {useEffect,useRef,useState} from 'react'
import type {SavedRender} from '@/lib/studio-render-record'
type Result={image:string;source:string;revision:string;id?:string}
export default function PhotorealisticRender({capture,title,revision,projectId,beforeGenerate}:{capture:()=>string|undefined;title:string;revision:string;projectId?:string;beforeGenerate?:()=>Promise<void>}){
 const [available,setAvailable]=useState(false),[busy,setBusy]=useState(false),[style,setStyle]=useState('Natural daylight, warm timber, soft neutral finishes, realistic architectural photography.'),[message,setMessage]=useState(''),[result,setResult]=useState<Result|null>(null),[history,setHistory]=useState<{id:string;createdAt:string}[]>([])
 const controller=useRef<AbortController|null>(null),generation=useRef(0)
 useEffect(()=>{const c=new AbortController();void fetch('/api/studio/recognise',{signal:c.signal}).then(r=>r.json()).then(d=>setAvailable(d.images===true)).catch(()=>{});return()=>c.abort()},[])
 useEffect(()=>{const c=new AbortController(),id=++generation.current;controller.current?.abort();setResult(null);setHistory([]);setBusy(false);setMessage('');if(projectId)void(async()=>{try{const r=await fetch('/api/studio/renders?projectId='+encodeURIComponent(projectId),{signal:c.signal,cache:'no-store'}),v=await r.json();if(!r.ok){if(r.status!==404)throw new Error(v.error);return}if(id!==generation.current)return;setHistory(v.renders);if(v.renders[0]){const image=await fetch('/api/studio/renders?projectId='+encodeURIComponent(projectId)+'&id='+v.renders[0].id,{signal:c.signal,cache:'no-store'}),data=await image.json();if(!image.ok)throw new Error(data.error);if(id===generation.current)setResult(data.render)}}catch(e){if(!c.signal.aborted&&id===generation.current)setMessage(e instanceof Error?e.message:'Saved images unavailable.')}})();return()=>{c.abort();controller.current?.abort();generation.current++}},[projectId])
 async function open(id:string){const run=++generation.current,c=new AbortController();controller.current?.abort();controller.current=c;setBusy(true);try{const r=await fetch('/api/studio/renders?projectId='+encodeURIComponent(projectId!)+'&id='+id,{signal:c.signal,cache:'no-store'}),v=await r.json();if(!r.ok)throw new Error(v.error);if(run===generation.current){setResult(v.render);setMessage('Saved image opened.')}}catch(e){if(run===generation.current)setMessage(e instanceof Error?e.message:'Could not open image.')}finally{if(run===generation.current)setBusy(false)}}
 async function generate(){if(!projectId)return;const source=capture();if(!source){setMessage('Wait for the 3D model to load.');return}const id=++generation.current,c=new AbortController();controller.current?.abort();controller.current=c;setBusy(true);setMessage('Saving your model, then generating its visualisation…');const timer=setTimeout(()=>c.abort(),225000);try{await beforeGenerate?.();c.signal.throwIfAborted();const r=await fetch('/api/studio/render',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image:source,style,title:title.slice(0,200),projectId,revision}),signal:c.signal}),v=await r.json();if(!r.ok)throw new Error(v.error);if(id===generation.current){const saved=v.render as SavedRender|null;setResult(saved||{image:v.image,source,revision});if(saved)setHistory(items=>[{id:saved.id,createdAt:saved.createdAt},...items]);setMessage(v.saveError||(saved?'Image saved to this project. '+v.label:'The image was generated but not saved. Download it before leaving this page.'))}}catch(e){if(id===generation.current)setMessage(c.signal.aborted?'Stopped waiting. Check saved images after the request finishes before generating again.':e instanceof Error?e.message:'Image generation failed.')}finally{clearTimeout(timer);if(id===generation.current)setBusy(false)}}
 return <details className="wb-photo-render"><summary>Photorealistic visualisation</summary><p>Generate from the current camera view and visible floors. The snapshot and preferences are sent to OpenAI. The editable model and estimate remain the measurement source.</p><label>Materials & lighting<textarea maxLength={1500} value={style} onChange={e=>setStyle(e.target.value)}/></label>{!projectId&&<p>Open the current project model to generate and save its images.</p>}{!available&&<p>Image generation is not yet connected on this installation. Previously saved images remain available.</p>}<button disabled={!projectId||!available||busy} onClick={()=>void generate()}>{busy?'Working on image…':'Generate photorealistic image'}</button>{busy&&<button onClick={()=>controller.current?.abort()}>Stop waiting</button>}{history.length>0&&<label>Saved images<select aria-label="Saved project images" disabled={busy} value={result?.id||''} onChange={e=>void open(e.target.value)}>{!result?.id&&<option value="">Choose a saved image</option>}{history.map(h=><option key={h.id} value={h.id}>{new Date(h.createdAt).toLocaleString('en-AU')}</option>)}</select></label>}{message&&<p role="status">{message}</p>}{result&&<><p>{!matchesJson(JSON.parse(revision),result.revision)?'This image belongs to an earlier model revision. ':''}Illustrative AI output — review against the model.</p><div className="wb-render-compare"><figure><img src={result.source} alt="Source model snapshot"/><figcaption>Model snapshot sent to the API</figcaption></figure><figure><img src={result.image} alt="AI architectural visualisation"/><figcaption>AI concept visualisation · not for measurement</figcaption></figure></div><a href={result.image} download="worka-ai-concept.png">Download visualisation</a><p>{result.id?'Saved privately with this project. Reopen it from Saved images.':'This image is not saved. Download it before leaving this page.'}</p></>}</details>
}
