'use client'
import {useState} from 'react'
import type {Workspace} from '@/lib/studio-workspace'
import {uid} from '@/lib/studio-workspace'
import {revise,totals} from '@/lib/project-studio'
import {scopeTemplates,newScopeReview,scopeIssues,addScopePlaceholder,benchmarkComparison} from '@/lib/studio-scope'
import type {ScopeReview as Review} from '@/lib/studio-scope'
const money=(n:number)=>n.toLocaleString('en-AU',{style:'currency',currency:'AUD',maximumFractionDigits:0})
export default function ScopeReview({workspace:w,onChange}:{workspace:Workspace;onChange:(w:Workspace)=>void}){
 const [documentName,setDocumentName]=useState(''),[error,setError]=useState('')
 const review=w.scopeReview,r=w.project.working
 const update=(patch:Partial<Review>)=>onChange({...w,scopeReview:{...review!,...patch}})
 if(!review)return <section className="wb-card"><h2>What’s included?</h2><p>Check document revisions and missing trades before treating this as a complete estimate.</p><button onClick={()=>onChange({...w,scopeReview:newScopeReview()})}>Start scope review</button></section>
 const issues=scopeIssues(review,r),comparison=benchmarkComparison(review,r,totals(r).total)
 return <details className="wb-card"><summary><strong>What’s included?</strong> · {issues.length?`${issues.length} to check`:'Scope recorded'}</summary><p>Confirm which drawings and work this estimate covers. Open a section to check the details.</p>
 <label>Type of work <select value={review.kind} onChange={e=>update({kind:e.target.value as Review['kind']})}><option value="unknown">Confirm project type</option><option value="new-build">Complete new build</option><option value="alterations">Alterations and additions</option><option value="mixed">Mixed / multiple buildings</option></select></label>
 <h3>Source documents</h3><p>Confirm which revisions govern the job. Registering a document does not upload or read its pages.</p>
 {review.documents.map((d,i)=><details className="wb-card" key={i}><summary>{d.name} · {d.status}</summary><label>Page count <input type="number" aria-label={`Pages for ${d.name}`} min="1" max="2000" value={d.pages} onChange={e=>{const pages=Number(e.target.value);if(Number.isInteger(pages)&&pages>0&&pages<=2000)update({documents:review.documents.map((x,j)=>j===i?{...x,pages}:x)})}}/></label><label>Revision / date <input aria-label={`Revision for ${d.name}`} value={d.revision} maxLength={200} onChange={e=>update({documents:review.documents.map((x,j)=>j===i?{...x,revision:e.target.value}:x)})}/></label> <label>Status <select aria-label={`Status for ${d.name}`} value={d.status} onChange={e=>update({documents:review.documents.map((x,j)=>j===i?{...x,status:e.target.value as typeof d.status}:x)})}><option value="unreviewed">Needs review</option><option value="current">Confirmed current</option><option value="superseded">Superseded — do not use</option></select></label><label>Review note <input aria-label={`Review note for ${d.name}`} value={d.note} maxLength={2000} onChange={e=>update({documents:review.documents.map((x,j)=>j===i?{...x,note:e.target.value}:x)})}/></label></details>)}
 <form onSubmit={e=>{e.preventDefault();if(!documentName.trim()||review.documents.length>=80)return;update({documents:[...review.documents,{name:documentName.trim(),pages:1,revision:'',status:'unreviewed',note:'Page count not yet checked.'}]});setDocumentName('')}}><label>Document name <input value={documentName} maxLength={250} onChange={e=>setDocumentName(e.target.value)}/></label> <button type="submit">Register document</button></form>
 <h3>Scope coverage</h3><p>Use “Link existing items” when work is already priced, to avoid counting it twice. Placeholder items start with no quantity and no price.</p>
 {scopeTemplates.map(([key,,name])=>{const item=review.items.find(s=>s.key===key)!;const change=(patch:Partial<typeof item>)=>update({items:review.items.map(s=>s.key===key?{...s,...patch}:s)});return <details className="wb-card" key={key}><summary>{name} · {item.status==='unknown'?'Needs decision':item.status} · {item.lineIds.length} linked</summary><label>Scope decision <select aria-label={`${name} decision`} value={item.status} onChange={e=>change({status:e.target.value as typeof item.status})}><option value="unknown">Needs decision</option><option value="included">Included</option><option value="excluded">Excluded</option></select></label><label>Drawing reference, assumption or exclusion reason <textarea aria-label={`${name} evidence`} maxLength={2000} value={item.note} onChange={e=>change({note:e.target.value})}/></label>{item.status==='included'&&<><label>Link existing items <select multiple aria-label={`Link items for ${name}`} value={item.lineIds} onChange={e=>change({lineIds:Array.from(e.target.selectedOptions,o=>o.value)})}>{r.lines.map(l=><option key={l.id} value={l.id}>{l.name}{l.included?'':' (excluded)'}</option>)}</select></label><button disabled={item.lineIds.some(id=>r.lines.some(l=>l.id===id))||r.lines.length>=500} onClick={()=>{try{const next=addScopePlaceholder(review,r,key,uid());onChange({...w,scopeReview:next.review,project:revise(w.project,{lines:next.lines})});setError('')}catch(e){setError((e as Error).message)}}}>Add unpriced scope item</button></>}</details>})}
 {error&&<p role="alert">{error}</p>}
 <h3>Independent benchmark</h3><p>A reported builder total is a comparison only. It never changes quantities, rates or your calculated estimate.</p>
 <label>Reported total including GST <input type="number" min="0" max="1000000000" value={review.benchmark?.totalInclGST||''} onChange={e=>{const total=Number(e.target.value);if(Number.isFinite(total)&&total>=0&&total<=1e9)update({benchmark:total?{totalInclGST:total,source:review.benchmark?.source||'',scopeConfirmed:false}:undefined})}}/></label>
 {review.benchmark&&<><label>Source / evidence <textarea maxLength={2000} value={review.benchmark.source} onChange={e=>update({benchmark:{...review.benchmark!,source:e.target.value,scopeConfirmed:false}})}/></label><label><input type="checkbox" checked={review.benchmark.scopeConfirmed} onChange={e=>update({benchmark:{...review.benchmark!,scopeConfirmed:e.target.checked}})}/> I have checked that the benchmark covers the same scope, allowances and exclusions.</label></>}
 {comparison&&<p><strong>{comparison.comparable?'Scope comparison':'Provisional comparison — not evidence of accuracy'}</strong><br/>Reported total {money(comparison.benchmark)} · Current priced items {money(comparison.estimate)} · Difference {money(comparison.difference)}. Both include GST. Missing quantities and prices can materially change this difference.</p>}
 </details>
}
