'use client'
import {useState} from 'react'
import type {Workspace} from '@/lib/studio-workspace'
import {money,revise} from '@/lib/project-studio'
import {preparePriceDraft,markupForTotal} from '@/lib/studio-price-draft'
export default function SimpleEstimate({workspace:w,onChange,onReview,onDetails}:{workspace:Workspace;onChange:(w:Workspace)=>void;onReview:()=>void;onDetails:()=>void}){
 const draft=preparePriceDraft(w.project.working,w.rates),t=draft.total
 const [amount,setAmount]=useState(''),[error,setError]=useState('')
 function apply(value:number){try{const markup=markupForTotal(draft.revision,value);onChange({...w,project:revise(w.project,{lines:draft.revision.lines,markup})});setError('')}catch(e){setError((e as Error).message)}}
 return <section className="wb-card wb-simple-estimate"><p className="wb-eyebrow">YOUR DRAFT ESTIMATE</p><h2>{t.cost>0?money(t.total):'Add your scope to start'}</h2><p>Total includes GST · {draft.missing?'Partial estimate — '+draft.missing+' items still need a price.':'For the included work; confirm scope before quoting.'}</p>{t.cost>0&&<><label htmlFor="estimate-price-slider">Adjust your selling price<input id="estimate-price-slider" type="range" min={Math.ceil(t.cost*1.1)} max={Math.floor(t.cost*2.2)} step="1" value={Math.round(t.total)} onChange={e=>{setAmount('');apply(Number(e.target.value))}}/></label><div className="wb-slider-labels"><span>Lower price</span><span>Higher price</span></div><label>Or enter total including GST<input type="number" min={t.cost*1.1} max={t.cost*2.2} step="0.01" value={amount||t.total} onChange={e=>setAmount(e.target.value)} onBlur={()=>{if(amount)apply(Number(amount))}} onKeyDown={e=>{if(e.key==='Enter'&&amount){apply(Number(amount));e.currentTarget.blur()}}}/></label><p>Estimated cost: {money(t.cost)} ex GST · Gross margin: {t.margin.toFixed(1)}%</p><p className="wb-hint">Moving the slider changes your selling price. Estimated costs stay the same. Lowest price covers estimated costs and GST.</p></>}{error&&<p role="alert">{error}</p>}<button className="wb-primary" disabled={t.cost<=0} onClick={()=>{if(amount){try{markupForTotal(draft.revision,Number(amount))}catch(e){setError((e as Error).message);return}}onChange({...w,project:revise(w.project,{lines:draft.revision.lines,markup:amount?markupForTotal(draft.revision,Number(amount)):draft.revision.markup})});onReview()}}>Review adjusted estimate →</button><button onClick={onDetails}>View breakdown</button><details><summary>How this estimate was prepared</summary><p>{draft.saved} saved builder rates proposed · {draft.suggested} new suggested allowances · {draft.missing} missing prices.</p><p>Standard timber framing, wall batts, one plasterboard face and internal painting are allowed where those items exist. Confirm wall construction, garage finishes, fire ratings and wet-area requirements. These allowances are not a verified reading of your plans. Existing prices are preserved. Other work remains unpriced.</p><p>Suggestions remain unreviewed. Adjusting the total does not confirm measurements, rates or scope.</p></details></section>
}
