'use client'
import {useRef,useState} from 'react'
import {parseWorkspace,type Workspace} from '@/lib/studio-workspace'
import {money,revise,quantity,lineCost,totals} from '@/lib/project-studio'
import {builderCostSummary} from '@/lib/studio-builder-estimate'
import {scopeTemplates} from '@/lib/studio-scope'
export default function SimpleEstimate({workspace:w,onChange,onReview,onDetails}:{workspace:Workspace;onChange:(w:Workspace)=>void;onReview:()=>void;onDetails:()=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[filter,setFilter]=useState('')
 const latest=useRef(w);latest.current=w
 const summary=builderCostSummary(w),review=w.builderReview,lines=w.project.working.lines
 const canPrepare=!!(lines.length||w.plan||w.drawings?.length||w.documentReadings?.length)
 async function prepare(){setBusy(true);setError('');const stamp=JSON.stringify(w),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),235000)
  try{const r=await fetch('/api/studio/price-draft',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workspace:w}),signal:controller.signal}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not prepare the draft.');if(JSON.stringify(latest.current)!==stamp)throw new Error('Your project changed. Your edits are preserved; prepare the estimate again.');const next=parseWorkspace(d.workspace);if(!next||next.project.id!==w.project.id)throw new Error('Invalid estimate. Your work is unchanged.');onChange(next)}catch(e){setError((e as Error).name==='AbortError'?'The estimate took too long. Your plans and existing work are saved; try again.':(e as Error).message)}finally{clearTimeout(timer);setBusy(false)}
 }
 function edit(id:string,field:'quantity'|'rate'|'labour',value:string){const n=Number(value);if(!Number.isFinite(n)||n<0||n>1e7)return;onChange({...w,project:revise(w.project,{lines:lines.map(l=>l.id===id?{...l,[field]:n,rateVerified:false}:l)})})}
 const missing=lines.filter(l=>l.included&&(l.rate+(l.labour||0)<=0||quantity(l,w.project.working.design)<=0)).length
 return <section id="builder-estimate" className="wb-card wb-builder-estimate" aria-busy={busy}>
  <p className="wb-eyebrow">BUILDER REVIEW · INTERNAL ESTIMATE</p><h2>{summary.cost>0?money(summary.cost)+' ex GST':'A starting estimate from your plans'}</h2>
  <p>{review?.summary||'WorkA proposes the job scope, quantities and ordinary cost allowances for you to review. A 3D model is optional.'}</p>
  <div className="wb-toolbar"><button className="wb-primary" disabled={busy||!canPrepare} onClick={()=>void prepare()}>{busy?'Preparing your builder estimate…':review?'Check for missing work':'Prepare builder estimate →'}</button><button disabled={busy} onClick={onDetails}>Full cost breakdown</button></div>
  <p className="wb-hint">Existing prices are kept. Suggested rates are general estimating allowances, not live supplier prices. Nothing is sent to a client.</p>
  {busy&&<p role="status">Reading the plans and building the scope, costs and assumptions. This can take a few minutes.</p>}{error&&<p role="alert">{error}</p>}
  {summary.cost>0&&<><div className="wb-builder-totals"><div><span>Estimated direct cost</span><strong>{money(summary.cost)}</strong></div><div><label>Design contingency %<input aria-label="Design contingency percentage" type="number" min="0" max="30" step="0.5" value={review?.contingencyPercent||0} disabled={!review||busy} onChange={e=>{const v=Number(e.target.value);if(review&&Number.isFinite(v)&&v>=0&&v<=30)onChange({...w,builderReview:{...review,contingencyPercent:v}})}}/></label><strong>{money(summary.reserve)}</strong></div><div><span>Cost including reserve · ex GST</span><strong>{money(summary.costWithReserve)}</strong></div></div>
  <p className="wb-hint">The reserve is separate from scope costs and client quote totals. Review it before preparing a client quote.{missing>0?' '+missing+' included items still need a quantity or price.':''}</p>
  <label>Find scope or assumptions<input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="e.g. roof, plumbing, retaining…"/></label>
  {[...scopeTemplates.map(s=>({key:s[0] as string,title:s[2]})),{key:'other',title:'Other existing scope'}].map(s=>{const items=lines.filter(l=>(s.key==='other'?!l.scopeKey:l.scopeKey===s.key)&&(!filter||(l.name+' '+l.note).toLowerCase().includes(filter.toLowerCase())));if(!items.length)return null;return <details className="wb-builder-trade" key={s.key} open={filter?true:undefined}><summary>{s.title}<span>{money(items.reduce((n,l)=>n+lineCost(l,w.project.working.design),0))}</span></summary><div className="wb-table-scroll"><table><thead><tr><th>Work item</th><th>Quantity</th><th>Material / sub rate</th><th>Labour rate</th><th>Cost ex GST</th></tr></thead><tbody>{items.map(l=><tr key={l.id}><td><strong>{l.name}</strong><small>{l.estimateType|| (l.allowance?'Allowance':'Existing price')} · {l.quantityBasis||(l.source==='entered'?'Entered quantity':'Model quantity')}{!l.included?' · Excluded':''}</small><details><summary>Basis & assumptions</summary><p>{l.note}</p></details></td><td>{l.source==='entered'?<input aria-label={l.name+' draft quantity'} type="number" min="0" step="any" value={l.quantity} disabled={busy} onChange={e=>edit(l.id,'quantity',e.target.value)}/>:quantity(l,w.project.working.design)} {l.unit}</td><td><input aria-label={l.name+' draft material rate'} type="number" min="0" step="any" value={l.rate} disabled={busy} onChange={e=>edit(l.id,'rate',e.target.value)}/></td><td><input aria-label={l.name+' draft labour rate'} type="number" min="0" step="any" value={l.labour||0} disabled={busy} onChange={e=>edit(l.id,'labour',e.target.value)}/></td><td>{money(lineCost(l,w.project.working.design))}</td></tr>)}</tbody></table></div></details>})}
  {review&&<><details><summary>Key assumptions & review priorities</summary><ul>{[...review.assumptions,...review.warnings].map((s,i)=><li key={i}>{s}</li>)}</ul></details><details><summary>Exclusions</summary><ul>{review.exclusions.map((s,i)=><li key={i}>{s}</li>)}</ul></details>{review.options.length>0&&<details><summary>Optional work · excluded from base cost</summary>{review.options.map((o,i)=><div className="wb-project-row" key={i}><span><strong>{o.name}</strong><small>{o.basis}</small></span><strong>+{money(o.cost)} ex GST</strong></div>)}</details>}<p className="wb-hint">PC = product allowance; PS = work whose extent is uncertain. Quantities and rates remain unreviewed until you check them.</p></>}
  <details><summary>Later: prepare a client quote</summary><p>Scope cost before the separate design reserve: {money(summary.cost)} ex GST. Current markup: {w.project.working.markup}%. Client quote workflow total: {money(totals(w.project.working).total)} including GST. Decide how to include the reserve before quoting.</p><button disabled={busy||missing>0} onClick={onReview}>Open client quote review</button></details></>}
 </section>
}
