'use client'
import {useState} from 'react'
type Rate={id:string;description:string;rate:number;unit:string;confirmed_at:string}
export default function ConfirmedRates(){
 const [rates,setRates]=useState<Rate[]>([]),[open,setOpen]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(false),[retiring,setRetiring]=useState<string|null>(null)
 async function load(){setLoading(true);setError('');try{const res=await fetch('/api/rates/confirmed');if(!res.ok)throw Error('Your saved rates could not be loaded');setRates((await res.json()).rates??[])}catch(e){setError(e instanceof Error?e.message:'Rates unavailable')}finally{setLoading(false)}}
 async function retire(id:string){setRetiring(id);setError('');try{const res=await fetch('/api/rates/confirmed',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});if(!res.ok)throw Error('Could not retire this rate. Please retry.');await load()}catch(e){setError(e instanceof Error?e.message:'Could not retire this rate')}finally{setRetiring(null)}}
 return <section className="mx-4 mb-4 p-4 rounded-xl" style={{border:'1px solid var(--bg-border)',background:'var(--bg-surface)'}}><button type="button" className="font-semibold w-full text-left" aria-expanded={open} onClick={()=>{setOpen(!open);if(!open)void load()}}>Your confirmed rates <span aria-hidden="true">{open?'−':'+'}</span></button>{open&&<><p className="text-xs mt-2" style={{color:'var(--text-secondary)'}}>Your pricing memory: only unit prices you explicitly confirmed. Worka matches the same scope and unit in future estimates. AI guesses are never saved here automatically.</p>{error&&<p role="alert" className="mt-3">{error}</p>}{loading&&<p role="status" className="mt-3 text-sm">Loading your rates…</p>}{rates.map(rate=>{const age=Math.max(0,Math.floor((Date.now()-Date.parse(rate.confirmed_at))/86400000));return <div key={rate.id} className="mt-3 pt-3 text-sm" style={{borderTop:'1px solid var(--bg-border)'}}><p>{rate.description}</p><p className="mt-1 font-semibold">{Number(rate.rate).toLocaleString('en-AU',{style:'currency',currency:'AUD'})} / {rate.unit}</p><p className="mt-1 text-xs" style={{color:'var(--text-secondary)'}}>Confirmed by you · {age===0?'today':age===1?'yesterday':`${age} days ago`}</p><button className="btn-secondary px-3 py-2 mt-2 text-xs" disabled={retiring!==null} onClick={()=>retire(rate.id)}>{retiring===rate.id?'Updating…':'Stop using this rate'}</button></div>})}{!rates.length&&!error&&!loading&&<p className="text-sm mt-3">No confirmed rates yet. Review an estimate item, save your price, then choose “Save as my rate”.</p>}<p className="text-xs mt-3" style={{color:'var(--text-secondary)'}}>Stopping reuse preserves your history. To change a price, edit its estimate item and save the rate again.</p></>}</section>
}
