/**
 * create-worker — Layer 2 Decision (Backend)
 *
 * Creates a new worker (crew member) record for a builder and generates
 * a unique invite URL. Returns a Layer 3 modal_event instructing the UI
 * to open the worker detail modal.
 *
 * Input:  POST { builder_id, name, role, email?, phone? }
 * Output: { worker: Worker, invite_url: string, modal_event: { type: 'open_worker_modal', worker_id } }
 */

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

// ─── Types ────────────────────────────────────────────────────

interface CreateWorkerRequest {
  builder_id: string
  name: string
  role: string
  email?: string
  phone?: string
}

interface Worker {
  id: string
  builder_id: string
  name: string
  role: string
  email: string | null
  phone: string | null
  status: string
  invite_token: string | null
  created_at: string
}

interface WorkerModalEvent {
  type: 'open_worker_modal'
  worker_id: string
}

interface CreateWorkerResponse {
  worker: Worker
  invite_url: string
  modal_event: WorkerModalEvent
}

// ─── CORS headers ─────────────────────────────────────────────

const CORS_HEADERS: Record<string, string> = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization',
}

function corsResponse(body: string, status = 200): Response {
  return new Response(body, {
    status,
    headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' },
  })
}

// ─── Handler ──────────────────────────────────────────────────

Deno.serve(async (req: Request): Promise<Response> => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { status: 204, headers: CORS_HEADERS })
  }

  if (req.method !== 'POST') {
    return corsResponse(JSON.stringify({ error: 'Method not allowed' }), 405)
  }

  let body: CreateWorkerRequest
  try {
    body = await req.json() as CreateWorkerRequest
  } catch {
    return corsResponse(JSON.stringify({ error: 'Invalid JSON body' }), 400)
  }

  const { builder_id, name, role, email, phone } = body

  // Validate required fields
  if (!builder_id || typeof builder_id !== 'string') {
    return corsResponse(JSON.stringify({ error: 'builder_id is required' }), 400)
  }
  if (!name || typeof name !== 'string' || name.trim().length === 0) {
    return corsResponse(JSON.stringify({ error: 'name is required' }), 400)
  }
  if (!role || typeof role !== 'string' || role.trim().length === 0) {
    return corsResponse(JSON.stringify({ error: 'role is required' }), 400)
  }

  const supabaseUrl = Deno.env.get('SUPABASE_URL')
  const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')
  if (!supabaseUrl || !supabaseServiceKey) {
    return corsResponse(JSON.stringify({ error: 'Supabase environment variables not configured' }), 500)
  }

  const supabase = createClient(supabaseUrl, supabaseServiceKey, {
    auth: { autoRefreshToken: false, persistSession: false },
  })

  try {
    // Verify the builder exists
    const { data: builder, error: builderError } = await supabase
      .from('builders')
      .select('id')
      .eq('id', builder_id)
      .single()

    if (builderError || !builder) {
      return corsResponse(JSON.stringify({ error: 'Builder not found' }), 404)
    }

    // Insert the worker — invite_token is auto-generated by DB default
    const { data: worker, error: insertError } = await supabase
      .from('workers')
      .insert({
        builder_id,
        name: name.trim(),
        role: role.trim().toLowerCase(),
        email: email?.trim() || null,
        phone: phone?.trim() || null,
        status: 'invited',
      })
      .select()
      .single()

    if (insertError || !worker) {
      console.error('Worker insert error:', insertError)
      return corsResponse(
        JSON.stringify({ error: 'Failed to create worker', detail: insertError?.message }),
        500
      )
    }

    // Build invite URL
    const appUrl = Deno.env.get('NEXT_PUBLIC_APP_URL') ?? 'https://app.worka.com.au'
    const invite_url = `${appUrl}/join/${worker.invite_token}`

    const result: CreateWorkerResponse = {
      worker: worker as Worker,
      invite_url,
      modal_event: {
        type: 'open_worker_modal',
        worker_id: worker.id,
      },
    }

    return corsResponse(JSON.stringify(result), 201)
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : 'Unknown error'
    console.error('create-worker error:', msg)
    return corsResponse(JSON.stringify({ error: 'Failed to create worker', detail: msg }), 500)
  }
})
